### ISSUE TITLE
图床CDN提供商jsdelivr在大陆不可访问了

### ISSUE THREAD

**Issue by G-haoyu** [XPoet/picx#101]
今天中午（2021.12.20）用图床的时候点CDN图片加载不出来，晚些时候得知是jsdelivr取消了中国IP节点，希望图床能跟进一下情况。

**Comment by GillianJiao** [comment]
已经拉闸了。没有意思了

**Comment by WEI-1228** [comment]
为啥我可以加载出来，很快

**Comment by XPoet** [comment]
jsdelivr 已在中国大陆恢复使用
