### ISSUE TITLE
组个群啊

### ISSUE THREAD

**Issue by jing5460** [XPoet/picx#11]
交流讨论

**Comment by XPoet** [comment]
挺好的建议，整一个

**Comment by XPoet** [comment]
❤️ 欢迎小伙伴们加入微信交流群~ ✿✿ヽ(°▽°)ノ✿

- 扫描下方二维码，加入微信交流群，欢迎小伙伴们畅所欲言，包括但不限于前端技术问题，大家一起成长~

  <img src="https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/PicX/image.1fa0oqlclbgg.png" width="45%" />

- 如果上面的二维码失效，可关注公众号《前端鼓励师》，添加作者微信，再由作者拉你进群~

  ![FEC-Card](https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/FE-Cheerleaders/FEC-Card.76dbi8n1bkk0.png)

**Comment by XPoet** [comment]
关于PicX 图床的任何问题和前端技术问题，都可以在群里提问，作者会积极为大家解答，同时，群里会经常分享学习干货、视频教程、面试指南等，也会经常给大家发红包，欢迎加入~━(*｀∀´*)ノ亻! 🌹🌹🌹
