### ISSUE TITLE
建议对gif图片不进行压缩

### ISSUE THREAD

**Issue by boluofan** [XPoet/picx#111]
默认配置的压缩很好用，但对于gif图片压缩后动态效果会失效。更改为不压缩图片后有动态效果。
建议压缩时候判断下，不对其进行压缩。

**Comment by XPoet** [comment]
好的，后续会优化

**Comment by XPoet** [comment]
该功能已实现，请使用 https://picx.xpoet.cn 进行上传图片，如果无效果，多刷新几次或清一下浏览器缓存
