### ISSUE TITLE
建议：自定义CDN

### ISSUE THREAD

**Issue by BakaJzon** [XPoet/picx#116]
反正要换，不如更进一步~

准备好几个变量，让用户自行编写
例： custom_CDN: https://cdn.example.com/gh/{user}/{repo}@{branch}/{filename}

**Comment by XPoet** [comment]
挺好的建议，后续会优化

**Comment by XPoet** [comment]
经过尝试，发现让用户填写自定义 CDN 规则目前不太友好，暂时不添加该功能

**Comment by XPoet** [comment]
经过尝试，发现让用户填写自定义 CDN 规则目前不太友好，暂时不添加该功能
