### ISSUE TITLE
后续会支持本地部署吗?

### ISSUE THREAD

**Issue by szxczyc** [XPoet/picx#12]
软件很好用，非常感谢！

**Comment by XPoet** [comment]
会，后续增加桌面端

**Comment by chinobing** [comment]
可以自己部署在vps吗？

**Comment by XPoet** [comment]
@chinobing 
可以，但不建议。使用作者提供的 PicX 官网拥有更好的体验，比如：及时的bug修复、新功能等等。
官网：picx.xpoet.cn

**Comment by chinobing** [comment]
> @chinobing
> 可以，但不建议。使用作者提供的 PicX 官网拥有更好的体验，比如：及时的bug修复、新功能等等。
> 官网：picx.xpoet.cn

对的，确实没有必要。我昨晚自己在VPS部署了，感觉就是多此一举。。。哈哈，后来就马上删了
