### ISSUE TITLE
建议:cdn更换为国内cdn

### ISSUE THREAD

**Issue by dndjdi** [XPoet/picx#124]
jsdelivr.panbaidu.cn
这个是国内刚出来的速度挺快的希望作者考虑一下

**Comment by XPoet** [comment]
好建议，我尽快抽空试一下，效果好的话会很快更新

**Comment by ctaoist** [comment]
这个已经凉了

**Comment by dndjdi** [comment]
嗯确实凉了，属实是没想到😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月8日(周日) 上午10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XPoet/picx] 建议:cdn更换为国内cdn (Issue #124)




 
这个已经凉了

**Comment by Eden-Lin** [comment]
没有凉吧？我可以ping通啊
