### ISSUE TITLE
不能上傳到4個以上的分目錄了？

### ISSUE THREAD

**Issue by mac88888** [XPoet/picx#127]
像1/1/1/1/1

現在只能三個 像 1/1/1

**Comment by XPoet** [comment]
暂时只支持到三级目录，会尽快开放到五级

**Comment by XPoet** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/24516169/228482928-e2092ebd-0ec7-4296-84ee-c412e8a45109.png">
