### ISSUE TITLE
压缩功能是不是出问题了

### ISSUE THREAD

**Issue by ych-chen** [XPoet/picx#130]
这几天上传不上去，发现是压缩的问题
把压缩关了就可以上传了，开了就一直上传不上去，希望检查一下

**Comment by XPoet** [comment]
@ych-chen 
我测试没有这个问题，截图看一下

**Comment by 2019087linghao** [comment]
确实，一压缩就卡的不行（三种都是）。卡死的那种
可以考虑本地压缩

**Comment by XPoet** [comment]
目前 PicX 内置的图片压缩是纯浏览器压缩，依靠的是硬件性能，当你的硬件性能比较一般时，压缩会有点卡顿，特别是 avif 编码。当然，你也可以选择使用其他第三方工具压缩之后再来上传（例如 [TinyPNG](https://tinypng.com/)）。

**Comment by XPoet** [comment]
我在只有 8G 运行内存的机子上测试都没问题，只有第一次压缩时慢了一点点，之后飞快。。
