### ISSUE TITLE
请求更新CDN, 或者是支持定义更换 CDN .

### ISSUE THREAD

**Issue by hankzhangcn** [XPoet/picx#137]
jsdelivr 在区域内较不稳定，已经不能很好地支持访问。

**Comment by XPoet** [comment]
已知悉，正在准备升级 PicX

**Comment by unravelyt** [comment]
+1

**Comment by XPoet** [comment]
PicX 已更新，现支持 **Staticaly CDN**

大家在 `设置 - CDN 提供商` 选择下 Staticaly CDN 即可，如果无效果，退出重新登录一下

![image](https://user-images.githubusercontent.com/24516169/176848900-d93dc131-5193-4b50-b9d9-da71ee6893d5.png)

![image](https://user-images.githubusercontent.com/24516169/176849489-8a5be60a-9be5-4b1e-8409-5251f3596c59.png)

**Comment by unravelyt** [comment]
大佬牛皮
