### ISSUE TITLE
Code: 401, Message: Bad credentials

### ISSUE THREAD

**Issue by 327506144** [XPoet/picx#138]
一直401是怎么回事？

**Comment by 327506144** [comment]
上周还好好的，这几天突然不行

**Comment by 327506144** [comment]
已经解决，需要先重置一下图床配置，然后重新验证token

**Comment by RealKiro** [comment]
@XPoet 刷新依然无法解决 , 无痕模式同样报错Code 401

浏览器：`Chrome 102.0.5005.61（正式版本） (x86_64)`
