### ISSUE TITLE
建议更新一下cdn

### ISSUE THREAD

**Issue by TransformersWsz** [XPoet/picx#139]
最近上传到github的图片，cdn外链已经失效了，图片加载不出来:
![image](https://user-images.githubusercontent.com/25796929/169565451-75049c59-6d7a-46ea-9845-8824e3e8d4b5.png)

**Comment by MssText** [comment]
确实 CDN挂掉了

**Comment by RubyXun** [comment]
这个cdn加速后的居然还要挂梯子才能正常访问

**Comment by XPoet** [comment]
作者这几天比较忙，很快就能抽出时间解决这个问题了，稍等片刻

**Comment by TransformersWsz** [comment]
> 作者这几天比较忙，很快就能抽出时间解决这个问题了，稍等片刻

辛苦作者👋

**Comment by Rr210** [comment]
> 这个cdn加速后的居然还要挂梯子才能正常访问

https://github.com/Rr210/blakeB2 试试这个图床 blake b2

**Comment by Rr210** [comment]
> 这个cdn加速后的居然还要挂梯子才能正常访问
https://github.com/Rr210/blazeB2 
https://secure.backblaze.com/b2_buckets.htm
这个可以就是速度不行

**Comment by XPoet** [comment]
PicX 已更新，现支持 **Staticaly CDN**

大家退出重新登录一下，在 `设置 - CDN 提供商` 选择下 Staticaly CDN 即可

![image](https://user-images.githubusercontent.com/24516169/176848900-d93dc131-5193-4b50-b9d9-da71ee6893d5.png)

![image](https://user-images.githubusercontent.com/24516169/176849489-8a5be60a-9be5-4b1e-8409-5251f3596c59.png)
