### ISSUE TITLE
上传后的图片怎么支持重命名啊

### ISSUE THREAD

**Issue by 2686259124** [XPoet/picx#14]
？？？？？？？？？？？？？

**Comment by XPoet** [comment]
目前不支持，你可以删了图片，重新命名后上传。

**Comment by 2686259124** [comment]
> 目前不支持，你可以删了图片，重新命名后上传。

希望下次可以出现这个功能，毕竟删除重新上传有点麻烦。。。

**Comment by XPoet** [comment]
后续会加上这个功能

**Comment by 2686259124** [comment]
> 后续会加上这个功能

感谢

**Comment by XPoet** [comment]
PicX 已支持图片重命名功能
![image](https://user-images.githubusercontent.com/24516169/147431094-0a643229-f21e-4b1d-a214-355a7274f8de.png)
![image](https://user-images.githubusercontent.com/24516169/147431115-d892fbfa-3f2a-419e-9ede-d30f00e038c9.png)
