### ISSUE TITLE
github外链和cdn加速过后的外链都需要【梯子】才能打开(已在码云重构)

### ISSUE THREAD

**Issue by RubyXun** [XPoet/picx#140]
# [我在码云优化部署了这个项目,着急使用的可以试下我的版本](https://gitee.com/rubyxun/picx-ruby)

### [访问地址](https://rubyxun.gitee.io/picx-ruby)

# 问题描述: 
================================================
### 仓库文件
![图片](https://user-images.githubusercontent.com/65531138/169755281-9b01d61c-37fc-4001-a137-de09e3108ac6.png)

(github)https://raw.githubusercontent.com/RubyXun/iFruit-Image/master/20220523/index_bg.7de6bhqjzhfk.jpg

(CDN)https://cdn.jsdelivr.net/gh/RubyXun/iFruit-Image@master/20220523/index_bg.7de6bhqjzhfk.jpg

**上面两个链接都需要梯子(cdn加速后的也是)才能打开**

**Statically CDN 这个加速后的就可以正常打开(无需翻墙)**
https://cdn.staticaly.com/gh/RubyXun/iFruit-Image@master/20220523/index_bg.7de6bhqjzhfk.jpg

### 建议作者更换cdn或者添加Statically CDN 
================================================

# [我在码云优化部署了这个项目,着急使用的可以试下我的版本](https://gitee.com/rubyxun/picx-ruby)

**Comment by RubyXun** [comment]
![图片](https://user-images.githubusercontent.com/65531138/169755487-1c8bca9c-f6cf-4db8-83de-b2b673cd9886.png)
cdn访问报错

**Comment by Lmmmmmm-bb** [comment]
> ![图片](https://user-images.githubusercontent.com/65531138/169755487-1c8bca9c-f6cf-4db8-83de-b2b673cd9886.png) cdn访问报错

我这貌似正常访问

**Comment by Lmmmmmm-bb** [comment]
> ![图片](https://user-images.githubusercontent.com/65531138/169755281-9b01d61c-37fc-4001-a137-de09e3108ac6.png) 仓库内有文件,但是图片链接却无法正常访问
> 
> https://raw.githubusercontent.com/RubyXun/iFruit-Image/master/20220523/index_bg.7de6bhqjzhfk.jpg
> 
> https://cdn.jsdelivr.net/gh/RubyXun/iFruit-Image@master/20220523/index_bg.7de6bhqjzhfk.jpg
> 
> 是需要等待时间吗?

cdn 需要时间同步

**Comment by RubyXun** [comment]
> > ![图片](https://user-images.githubusercontent.com/65531138/169755487-1c8bca9c-f6cf-4db8-83de-b2b673cd9886.png) cdn访问报错
> 
> 我这貌似正常访问

把梯子下了试试

**Comment by Lmmmmmm-bb** [comment]
> > > ![图片](https://user-images.githubusercontent.com/65531138/169755487-1c8bca9c-f6cf-4db8-83de-b2b673cd9886.png) cdn访问报错
> > 
> > 
> > 我这貌似正常访问
> 
> 把梯子下了试试

确实不行，最近 jsdelivr 都不太稳定，有给墙的风险

**Comment by RubyXun** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/65531138/169755487-1c8bca9c-f6cf-4db8-83de-b2b673cd9886.png) cdn访问报错
> > > 
> > > 
> > > 我这貌似正常访问
> > 
> > 
> > 把梯子下了试试
> 
> 确实不行，最近 jsdelivr 都不太稳定，有给墙的风险

Statically CDN 这个倒是可以
https://cdn.staticaly.com/gh/RubyXun/iFruit-Image@master/20220523/index_bg.7de6bhqjzhfk.jpg
试试这个cdn链接(不用梯子)

**Comment by Eden-Lin** [comment]
我也一样cdn.jsdelivr.netping不通，试了下这个cnd地址可以ping通：fastly.jsdelivr.net

**Comment by Eden-Lin** [comment]
请问在哪个文件里可以修改这个配置呢？

**Comment by RubyXun** [comment]
> 请问在哪个文件里可以修改这个配置呢？

我已经发了pull request

**Comment by RubyXun** [comment]
> 请问在哪个文件里可以修改这个配置呢？

https://rubyxun.gitee.io/picx-ruby
试下我在码云重构的吧

**Comment by XPoet** [comment]
作者这几天比较忙，很快就能抽出时间解决这个问题了，稍等片刻

**Comment by Eden-Lin** [comment]
> > 请问在哪个文件里可以修改这个配置呢？
> 
> https://rubyxun.gitee.io/picx-ruby 试下我在码云重构的吧

大佬，我想问下，我们在github上创建的public图床仓库，任何人都能访问到，要怎么保障隐私安全呢？

**Comment by Eden-Lin** [comment]
> > 请问在哪个文件里可以修改这个配置呢？
> 
> 我已经发了pull request

再请问下，我用作者的代码fork过来打包上传到docker容器里，自己部署的服务，为什么在PC端无法显示缩略图？也是跟CND加速有关么？

**Comment by RubyXun** [comment]
> > > 请问在哪个文件里可以修改这个配置呢？
> > 
> > 
> > 我已经发了pull request
> 
> 再请问下，我用作者的代码fork过来打包上传到docker容器里，自己部署的服务，为什么在PC端无法显示缩略图？也是跟CND加速有关么？

是cdn的问题,里面的图片链接都是经过那个有问题的cdn

**Comment by RubyXun** [comment]
> > > 请问在哪个文件里可以修改这个配置呢？
> > 
> > 
> > https://rubyxun.gitee.io/picx-ruby 试下我在码云重构的吧
> 
> 大佬，我想问下，我们在github上创建的public图床仓库，任何人都能访问到，要怎么保障隐私安全呢？

首先要保证图片链接公开就必须public仓库所以这个问题我还没有想法解决

**Comment by Eden-Lin** [comment]
> 

大佬，能不能把你的picx  ruby版本打个镜像推到docker hub上？

**Comment by RubyXun** [comment]
> docker hub

gitee挺好用的,我这边的docker环境还没完善,暂时不考虑

**Comment by origami-tech** [comment]
马云也开启反盗链了
