### ISSUE TITLE
 Code: 401, Message: Bad credentials

### ISSUE THREAD

**Issue by lys0214** [XPoet/picx#147]
配置自己的token还是不可用呢

**Comment by Lmmmmmm-bb** [comment]
> 配置自己的token还是不可用呢

生成 token 的时候勾选 repo 选项了吗

**Comment by lys0214** [comment]
生成token之前已经勾选了repo

然后复制过图床配置那边不好使！！不知道为舍了，之前还是好好使的呢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 中午12:21
收件人: ***@***.***&gt;; 
抄送: "‭  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XPoet/picx]  Code: 401, Message: Bad credentials (Issue #147)





  
配置自己的token还是不可用呢
  
生成 token 的时候勾选 repo 选项了吗

**Comment by Lmmmmmm-bb** [comment]
你过几分钟或者把浏览器缓存清了再试试
