### ISSUE TITLE
CDN无效

### ISSUE THREAD

**Issue by wlswang** [XPoet/picx#152]
使用CDN链接图片不显示

**Comment by XPoet** [comment]
PicX 刚刚已更新，现支持 Staticaly CDN

退出重新登录一下，在设置 - CDN 提供商选择下 Staticaly CDN 即可

![image](https://user-images.githubusercontent.com/24516169/176848900-d93dc131-5193-4b50-b9d9-da71ee6893d5.png)

![image](https://user-images.githubusercontent.com/24516169/176849489-8a5be60a-9be5-4b1e-8409-5251f3596c59.png)
