### ISSUE TITLE
为什么不能上传图片了呢？

### ISSUE THREAD

**Issue by tan45du** [XPoet/picx#16]
今天怎么都上传不进去，一直失败

**Comment by XPoet** [comment]
@tan45du 你的网络问题，GitHub 有时候会处于被墙的状态。
翻墙试试

**Comment by WorldlineChanger** [comment]
我也是，开了全局也提示 Code: 422, Message: Invalid request. "sha" wasn't supplied.

**Comment by XPoet** [comment]
@WorldlineChanger 
@tan45du 

刚刚作者测试了下，也出现上传失败的错误，可能是 GitHub 方面做了改动，作者正在排查错误....

**Comment by WorldlineChanger** [comment]
@XPoet 
辛苦了

**Comment by XPoet** [comment]
@WorldlineChanger 
@tan45du 

果然 GitHub 方面做了改动，上传已修复。
多刷新几次或清除缓存再试

**Comment by WorldlineChanger** [comment]
@XPoet 感谢大佬~
