### ISSUE TITLE
能否一次快速导出图床目录下所有图片的连结?

### ISSUE THREAD

**Issue by Arcelibs** [XPoet/picx#160]
假设使用jsdelivr代理，希望能快速导出一个清单的功能

例如這樣
https://cdn.jsdelivr.net/gh/Arcelibs/Image/13dsasdad1.png
https://cdn.jsdelivr.net/gh/Arcelibs/Image/1bbxcxvxcvc.jpg
https://cdn.jsdelivr.net/gh/Arcelibs/Image/21fdf444423fc.png

现在都要一个一个按去储存，有点麻烦

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/178171769-b53da4df-74ec-48d1-b7f1-8234b55eeeb6.png)

PicX 目前支持该功能的
