### ISSUE TITLE
新申请的token也不行，一直401

### ISSUE THREAD

**Issue by quinhua** [XPoet/picx#162]
Code: 401, Message: Bad credentials

**Comment by XPoet** [comment]
1、仓库是不是 public 的？
2、token 有没有开启 repo 权限？
3、用的什么浏览器？
4、打开浏览器控制台，把报错信息发出来

**Comment by RealKiro** [comment]
> 1、仓库是不是 public 的？ 2、token 有没有开启 repo 权限？ 3、用的什么浏览器？ 4、打开浏览器控制台，把报错信息发出来

- **我也是401**

@XPoet 
1. 是public

![image](https://user-images.githubusercontent.com/33367701/182110908-610dcf4a-00f5-4f06-bc5d-0b751a7d57ed.png)

2. 已开启repo 
![image](https://user-images.githubusercontent.com/33367701/182110988-65d223b6-afb8-45da-b11f-e750a8624e37.png)

3. Chrome 版本 103.0.5060.134（正式版本） (x86_64) 
![image](https://user-images.githubusercontent.com/33367701/182111078-a1c2d1cd-a9b8-47b9-a6fa-30f091af0e59.png)

4. 
![image](https://user-images.githubusercontent.com/33367701/182111520-a4df1aa4-144b-4fb0-a273-fe0f68d1f1f0.png)
