### ISSUE TITLE
png格式不支持吗？

### ISSUE THREAD

**Issue by Chairowell** [XPoet/picx#163]
需要使用背景透明的图片怎么办，因为需要兼容性好，webp格式无法使用（Safari）

**Comment by XPoet** [comment]
支持！

![image](https://user-images.githubusercontent.com/24516169/179516153-8450a35e-ca59-485e-9375-0f95e519577b.png)

你可以在 “我的设置” 里面把压缩图片的功能关闭即可

**Comment by XPoet** [comment]
建议使用 Chrome 浏览器

**Comment by Chairowell** [comment]
这样的吗
ok


&nbsp;


是一只栗子啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XPoet/picx] png格式不支持吗？ (Issue #163)





 
支持！
 

 
你可以在 “我的设置” 里面把压缩图片的功能关闭即可
