### ISSUE TITLE
TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by quinhua** [XPoet/picx#165]
TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

这是啥情况

**Comment by XPoet** [comment]
你是不是在 https://picx.xpoet.cn 使用抛出这个错误？
提供一下浏览器及版本。
控制台报错信息截图发一下

**Comment by quinhua** [comment]
![XRRS@E8W_AD~WF$1D7}M3}9](https://user-images.githubusercontent.com/49524392/183329486-ac77e173-16ca-4294-828e-21cafa60d2db.png)

**Comment by quinhua** [comment]
控制台并无报错，但是页面给出了

**Comment by XPoet** [comment]
你用 Google Chrome 浏览器，重新生成新的 GitHub Token 再试试
