### ISSUE TITLE
请问Cloudflare加速源是直接反代 Github 网站并套了 Cloudflare CDN 么？

### ISSUE THREAD

**Issue by BNQDZJ** [XPoet/picx#166]
请问Cloudflare加速源是直接反代 Github 网站并套了 Cloudflare CDN 么？
不建议这样干，参考 https://github.com/XIU2/UserScript/issues/261
如果要做加速源的话，建议搭建 https://github.com/hunshcn/gh-proxy 项目，这个没有风险。

**Comment by XPoet** [comment]
Cloudflare 加速已移除
