### ISSUE TITLE
请问图床管理的图经常是裂开的，但是链接都可以正常使用

### ISSUE THREAD

**Issue by jankin12138** [XPoet/picx#168]
遇到这个问题应该如何解决，管理起来不太方便，点开图片都是显示image not found，但实际上可以正常使用链接就是在网站看不到，仓库里也可以正常看到

**Comment by XPoet** [comment]
退出重新登录一下，
在设置里切换一下 CDN
<img width="804" alt="image" src="https://user-images.githubusercontent.com/24516169/189252348-efd6fd8a-358d-4795-9a95-06cde830c38d.png">
