### ISSUE TITLE
1.加个需求图片外链：2.buz不能选择原来的仓库

### ISSUE THREAD

**Issue by mj5219054** [XPoet/picx#170]
已看原文文档能操作仓库但是不能选择原来存库好的仓库。

**Comment by ounw** [comment]
可以更改为原来的仓库啊，首先你原来的仓库要是公开的，其次你要在设置里面更改连接仓库的配置为原来仓库的名称。

**Comment by Sunburst5** [comment]
> 可以更改为原来的仓库啊，首先你原来的仓库要是公开的，其次你要在设置里面更改连接仓库的配置为原来仓库的名称。

请问能详细说一下操作方法吗？试了下好像只能使用cdn 而目前cdn全挂了 其实直接用GitHub的链接也未尝不可

**Comment by XPoet** [comment]
请使用最新版 PicX 并同时清空下浏览器缓存，目前的 CDN 外链都是可用的
