### ISSUE TITLE
建议上传和复制链接都加个键盘快捷键

### ISSUE THREAD

**Issue by TZN2018** [XPoet/picx#173]
在粘贴上图片后要鼠标点上传按钮，再点复制链接，感觉还可再省去这两个步骤，直接将链接地址放入剪贴板更好，因为用哪个CDN以及用直链还是markdown链是提前设置的，一般不会混着用。

如觉得有必要在上传前人工确认，是否能加设上传和复制链接的键盘快捷键，以方便用键盘快速操作。

**Comment by XPoet** [comment]
挺好的建议，优化开发

**Comment by TZN2018** [comment]
感谢XPoet的创作，特别是附带的图片压缩功能比其他同类软件都好，我是嵌入到Quicker中达到复制图片后一键上传并获取图链的，升级前为达到自动化，上传后要设置N个Tab键和Enter键来达到自动点击上传按钮和获取CDN链，由于软件延迟经常出错，升级后只需设置一个 ctrl + s 就能轻松上传并获取链接，完全达到了高准确率地一键将粘贴板中图片变为超链的功能。再次感谢!
