### ISSUE TITLE
添加gogs、gitea支持，提供自定义baseURL

### ISSUE THREAD

**Issue by Antisunny** [XPoet/picx#174]
当前gogs api还不支持 put contents可以需要等支持了再支持。但其他与GitHub兼容的API可以提供自定义baseURL，方便配置，而不要写死。

**Comment by XPoet** [comment]
PicX 现已支持自定义配置图片链接规则，由于此次版本升级较大，请清空一下浏览器缓存再使用。
在线使用入口：https://picx.xpoet.cn

<img width="946" alt="image" src="https://user-images.githubusercontent.com/24516169/228482373-24bd0b52-430b-4379-be2b-7f78fe4c89ff.png">
