### ISSUE TITLE
能否支持组织仓库的选择

### ISSUE THREAD

**Issue by CCKNBC** [XPoet/picx#18]
能否支持组织仓库的选择，不想把图床换到账号仓库下

**Comment by XPoet** [comment]
@CCKNBC 
不太理解组织仓库选择

**Comment by zjwo** [comment]
> @CCKNBC
> 不太理解组织仓库选择

他的意思是用組織下的倉庫當作圖床，而不是個人下的倉庫

![image](https://user-images.githubusercontent.com/73284962/107522735-f31bb580-6bee-11eb-9d30-0be7ba3d4965.png)

**Comment by XPoet** [comment]
应该可以，待我找时间测试一下，可以的话，把这个功能加上去

**Comment by XPoet** [comment]
经作者反复推敲和其他用户反馈，完全没必要使用组织仓库来充当图床，该 Issue 关闭
