### ISSUE TITLE
Cloudflare生成的链接无法访问

### ISSUE THREAD

**Issue by cenxiaodong** [XPoet/picx#180]
上传图片后生成的Cloudflare无法访问

**Comment by Liqiuking** [comment]
对的

**Comment by XPoet** [comment]
原 Cloudflare CDN 已移除，新增 zzko CDN（China jsDelivr）

<img width="470" alt="image" src="https://user-images.githubusercontent.com/24516169/213471835-ba3b9e6a-1801-45f8-93f1-2c38fafbb149.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/24516169/213471914-b74a45d0-ad17-446b-a9c3-5b34ee105ef5.png">
