### ISSUE TITLE
把picx打包成utools插件

### ISSUE THREAD

**Issue by lovezsh** [XPoet/picx#183]
个人需求，基于本项目打包成utools插件，可以更方便的上传图片以及进行管理。

根据开源协议注明了出处和作者。

![image](https://user-images.githubusercontent.com/65840178/206437290-3c685f08-c68b-4cce-8b41-cb7f934ce06d.png)

**Comment by sxh705** [comment]
慕名而来, 点了点star

**Comment by XPoet** [comment]
感谢推广，制成其他渠道的第三方工具时请不要更名，统一为：PicX 图床

**Comment by xiaozhang959** [comment]
老哥，这个插件你怎么下架了，能否继续支持一下？  在这膜拜一下大佬

**Comment by lovezsh** [comment]
@xiaozhang959 之前是用iframe嵌套的，发现有些问题，每次打开token都会清掉，后面就下架了。

**Comment by XPoet** [comment]
后续作者会重新上架

**Comment by xiaozhang959** [comment]
> 后续作者会重新上架

期待一下
