### ISSUE TITLE
请问支持gitlab吗，还有可以配置typroa吗？

### ISSUE THREAD

**Issue by hoochanlon** [XPoet/picx#185]
另外我在网上了解到squooch和图压，图片压缩很快，图片质量也保持不错，picx有试参考过他们的压缩方案吗？

**Comment by XPoet** [comment]
1、暂不支持 GitLab，不支持在 Typroa 中配置。
2、目前 PicX 中压缩算法还行，在浏览器端达成的压缩比足够优秀，暂时没时间和精力去研究其他的。

**Comment by TNXG** [comment]
Typroa 使用的是PicGO，应该详细去康康picgo是否有支持的插件（其实有直接的github图床（

**Comment by hoochanlon** [comment]
目前的方案，看来也只能这样了。要不大佬联系下typroa，下个版本更新什么的，支持一下PicX。

**Comment by andyhuai** [comment]
要支持typroa需要提供API接口吧，纯前端估计不能提供API
