### ISSUE TITLE
希望能支持在上传界面中选择上传的目录

### ISSUE THREAD

**Issue by MagicalZhu** [XPoet/picx#187]
多级目录上传图片,需要先去配置界面修改指定的目录,然后再去上传界面上传。希望能在上传界面就直接选择已有的目录,如果没有是否可以考虑增加直接创建的功能?

**Comment by XPoet** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/24516169/217246964-dc3325ea-7225-4db8-b0f4-9ddb8bee0380.png">

**Comment by MagicalZhu** [comment]
> 目前支持上传到多级目录，参考下图：
> 
> <img alt="image" width="873" src="https://user-images.githubusercontent.com/24516169/217246964-dc3325ea-7225-4db8-b0f4-9ddb8bee0380.png">

了解,是这样的,希望大佬可以在上传图片界面可以直接选择目录,大概类似于这种
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/19918751/217276668-3c1d7a76-9af0-4825-9602-97cd4007ea30.png">

**Comment by XPoet** [comment]
下个版本迭代

**Comment by XPoet** [comment]
PicX 图床现已支持在上传页面重新选择仓库目录，由于此次版本升级较大，请清空一下浏览器缓存再使用
在线使用入口：https://picx.xpoet.cn

**Comment by XPoet** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/24516169/228483592-fef9c614-b9c1-4dbc-aa9c-09f8ffa3b259.png">

**Comment by MagicalZhu** [comment]
> <img alt="image" width="966" src="https://user-images.githubusercontent.com/24516169/228483592-fef9c614-b9c1-4dbc-aa9c-09f8ffa3b259.png">

可以了,大佬辛苦了 XD
