### ISSUE TITLE
会否支持 “细粒度的个人访问令牌”（Fine-grained personal access tokens ）？

### ISSUE THREAD

**Issue by LawssssCat** [XPoet/picx#192]
会否支持 “细粒度的个人访问令牌”（Fine-grained personal access tokens ）？

![image](https://user-images.githubusercontent.com/18041500/221457304-f051b799-a5bc-4837-a75e-830d19686e1a.png)

**Comment by XPoet** [comment]
待测试，后续版本会考虑

**Comment by sdokio** [comment]
老哥这个翻译很好阿，“细粒度的个人访问令牌”
