### ISSUE TITLE
⚠️ 注意：PicX `v2.3.3` 已发布，为确保正常使用，请刷新页面或清空下缓存后使用

### ISSUE THREAD

**Issue by XPoet** [XPoet/picx#198]
PicX 图床 v2.3.3 版本升级较大，为确保正常使用：
1. **请大家清空浏览器缓存之后再使用**
2. **退出登录，重新配置图床**

**在线使用入口：https://picx.xpoet.cn**

**Comment by XPoet** [comment]
各位小伙伴在使用过程中遇到问题，可以在该 Issue 下留言

**Comment by Salmonberry** [comment]
点击选择仓库时，只显示数个已公开的仓库（不包括之前用做图床仓库在内），无法设置之前配置的图床仓库作为图床仓库。

**Comment by XPoet** [comment]
@Salmonberry 
可以用之前的仓库。你要用手动配置
PicX 选择仓库列表可以显示前 100 个公开的仓库，你之前的图床仓库是不是设置是私有仓库了？检查下。
点击重置，重新配置一下试试

**Comment by XPoet** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/24516169/228521027-22f52069-54c3-404c-9e5e-dfd282655e6b.png">

**Comment by Salmonberry** [comment]
> PicX 图床 v2.2.0 版本升级较大，为确保正常使用：
> 
> 1. **请大家清空浏览器缓存之后再使用**
> 2. **退出登录，重新配置图床**
> 
> **在线使用入口：https://picx.xpoet.cn**

我是按照你说的重置过设置了，之后再执行后续的手动配置。
- 我配置的图床是一直都是public的，而且配置仓库处显示能选择的仓库只有7个，这远少于我公开的仓库数目
- 这个问题我分别在Win10和Mac上使用Chrome、Edge执行同样的操作，得出的结果都是一样的，都是只有同样的7个仓库可供我选择。

**Comment by Salmonberry** [comment]
> 

可以的

**Comment by XPoet** [comment]
@Salmonberry 
我发现问题了，已发布新版，你清一下浏览器缓存，重新手动配置试试看

在线使用入口：https://picx.xpoet.cn

**Comment by Salmonberry** [comment]
> 



> 

谢谢。我试过了，可以了。那我将刚发你的token delete 一下。

**Comment by sakura745** [comment]
清除了缓存还是打不开啊
![Screenshot from 2023-04-02 14-58-33](https://user-images.githubusercontent.com/49824526/229337774-83a7b112-23b3-4a3a-be74-9946d0058aeb.png)

**Comment by sakura745** [comment]
> 清除了缓存还是打不开啊 ![Screenshot from 2023-04-02 14-58-33](https://user-images.githubusercontent.com/49824526/229337774-83a7b112-23b3-4a3a-be74-9946d0058aeb.png)

后续可以了，就是要等的时间很长

**Comment by XPoet** [comment]
@sakura745 可能是你当时的网络环境不太好，偶现性问题。
你可以安装一下  PicX 图床的 PWA 程序。
<img width="545" alt="image" src="https://user-images.githubusercontent.com/24516169/229393781-bb6132a5-c185-491b-b06c-395728042fe6.png">

**Comment by sakura745** [comment]
> @sakura745 可能是你当时的网络环境不太好，偶现性问题。 你可以安装一下 PicX 图床的 PWA 程序。 <img alt="image" width="545" src="https://user-images.githubusercontent.com/24516169/229393781-bb6132a5-c185-491b-b06c-395728042fe6.png">

好的。

**Comment by dwfrost** [comment]
点击上传后报错，这个接口404了。
https://api.github.com/repos/dwfrost/images/contents/20230621/p2.4pq77pmhb1u0.png
![image](https://github.com/XPoet/picx/assets/26833988/15b0d739-8c3d-4d2d-a8e8-1b009e186ba2)

**Comment by dwfrost** [comment]
> 点击上传后报错，这个接口404了。 https://api.github.com/repos/dwfrost/images/contents/20230621/p2.4pq77pmhb1u0.png ![image](https://user-images.githubusercontent.com/26833988/247510449-15b0d739-8c3d-4d2d-a8e8-1b009e186ba2.png)

重新生成token就可以了
