### ISSUE TITLE
前端部署

### ISSUE THREAD

**Issue by zui-lang** [XPoet/picx#209]
希望可以通过vercel进行部署前段页面，通过bit.io等免费数据库保存数据，这样可以达到多端同步图床的功能

**Comment by XPoet** [comment]
- 不推荐使用额外部署的第三方站点，PicX 在持续维护和迭代中，使用 https://picx.xpoet.cn 即可。
- PicX 已内置多端同步的功能，在图床管理页面点击右上角按钮即可同步，如下图。
 
  <img width="910" alt="image" src="https://user-images.githubusercontent.com/24516169/232440088-592c4a8e-f3ca-407f-bf4b-ae02944d726f.png">

**Comment by zui-lang** [comment]
大佬，水印好像有字数限制？那个可以改一下吗，想把整个博客域名写上，字数可能多点，然后能否提供水印字体和颜色的修改

**Comment by XPoet** [comment]
你对图片水印有新的功能需求，请单独开 Issue，作者会根据 Issue 来迭代。
