### ISSUE TITLE
上传出错

### ISSUE THREAD

**Issue by superweb2021** [XPoet/picx#21]
提示
Code: 422, Message: Invalid request. For 'properties/email', nil is not a string.

上传失败！

**Comment by XPoet** [comment]
@superweb2021 

点击右上角的头像 -> 退出登录，重新配置图床，再试试上传

**Comment by WorldlineChanger** [comment]
@superweb2021 

可以了吗，我这边还是不行

**Comment by Zephyr-29** [comment]
我也还是不行

**Comment by jialezi666** [comment]
我的也不行

**Comment by jialezi666** [comment]
> 我的也不行

好了，我设置问题
https://github.com/settings/profile 里面的Public email没设置，

**Comment by XPoet** [comment]
大家在 https://github.com/settings/profile  设置一下邮箱，然后退出，登录使用 token 登录。可能是 GitHub 层面设了限制，没设置邮箱会上传失败

**Comment by XPoet** [comment]
该 Bug 已修复，现在不填邮箱也能上传成功了。
