### ISSUE TITLE
希望增加上传图片水印设置的更多选项

### ISSUE THREAD

**Issue by zui-lang** [XPoet/picx#213]
1. 水印字数限制可更改
2. 水印颜色
3. 水印字体（最好可以自定义字体，有字体上传功能）

**Comment by XPoet** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/24516169/234786324-d1a10ed7-fe93-40d7-b33d-48ff053edba2.png">

PicX `v2.3.3` 已发布，增强了水印配置项。
进入 https://picx.xpoet.cn 刷新页面即可

**Comment by XPoet** [comment]
当前版本水印字体限制在 20 字以内，如果还不够用，后续会再次开发限制
