### ISSUE TITLE
添加失败，该图片链接规则不合法

### ISSUE THREAD

**Issue by lovezsh** [XPoet/picx#218]
域名是我个人对GitHub仓库的链接做了处理，只需要一个path参数写规则，但是保存不合法，是不是做了限制，必须要启用所有参数才可与。

![image](https://user-images.githubusercontent.com/65840178/233788161-f849e20a-9eee-49ca-81d9-4eef863b2aa9.png)

**Comment by XPoet** [comment]
目前是做了限制，自定义的链接规则要包含 owner、repo、branch、path

**Comment by lovezsh** [comment]
> 目前是做了限制，自定义的链接规则要包含 owner、repo、branch、path

@XPoet 有什么方案可以取消限制吗，如上，我对域名做了处理，只需要一个 path

**Comment by XPoet** [comment]
等一下版本，我解除一些限制，下个小版本升级会这几天内发布

**Comment by XPoet** [comment]
PicX `v2.3.3` 已发布，完善了自定义图片链接规则配置，现已支持只填入 `{{path}}`。
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/24516169/234788122-62f2b378-eb61-48ee-87d5-f1daf5538428.png">

请进入 https://picx.xpoet.cn 刷新一下即可
