### ISSUE TITLE
SOS*图片加载不出来？

### ISSUE THREAD

**Issue by itscolor** [XPoet/picx#219]
图片用于Halo2.4博客中，但是一直加载不出来，请问开发者如何解决？不想再重新保存图片去传到博客了。谢谢~
我的博客地址：https://blog.oneleaf.asia/

**Comment by XPoet** [comment]
请提供你的图片链接

**Comment by itscolor** [comment]
> 请提供你的图片链接

https://jsd.cdn.zzko.cn/gh/itscolor/picx-images-hosting@master/【磕剧】/海报墙.g4ycm6vx4dk.webp

**Comment by XPoet** [comment]
不要使用中文命名

**Comment by XPoet** [comment]
把你博客中的图片链接 `https://jsd.cdn.zzko.cn`  替换成 `https://cdn.staticaly.com` 即可，可以使用编辑器全局一次性替换。

在 PicX 中使用复制图片链接时，选择 **Staticaly**

<img width="867" alt="image" src="https://user-images.githubusercontent.com/24516169/234789207-2d3b43b9-8aa8-4958-800f-ec328284d433.png">
