### ISSUE TITLE
jsd 50 MB 限制问题

### ISSUE THREAD

**Issue by HowieHye** [XPoet/picx#22]
![image](https://user-images.githubusercontent.com/36627364/111576161-e2142480-87ea-11eb-8b6f-b002849598ce.png)
![image](https://user-images.githubusercontent.com/36627364/111576181-ecceb980-87ea-11eb-9d70-1e28dea7dc49.png)

之前是使用手动发布release来解决这个问题的，希望picx能够很好地解决这个问题

**Comment by XPoet** [comment]
图片压缩是 PicX 下一步要做的事，以后通过 PicX 上传的图片，超过 50MB的，将会自动压缩

**Comment by chenyaofo** [comment]
希望能够通过自动添加分支或者发布release的方式突破这个50M的限制

**Comment by li1191863273** [comment]
希望能够通过自动添加分支或者发布release的方式突破这个50M的限制

**Comment by hmsjy2017** [comment]
@chenyaofo @li1191863273 国内release的下载速度令人担忧

**Comment by XPoet** [comment]
大于 50MB 的图片，作者已在 PicX 上传时进行了提醒，不压缩禁止上传。
大家可以使用免费的  [TinyPNG](https://tinypng.com/) 进行压缩，这是作者用过最好用的图片压缩工具。
暂时就用这种方案。

**Comment by XPoet** [comment]
作者已尝试过纯前端图片压缩，效果极差，强烈建议使用 [TinyPNG](https://tinypng.com/)
