### ISSUE TITLE
优化修改配置后的提示

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#225]
首先感谢作者的工具 ❤️ 

发现有的配置项修改需要点击确定按钮，有的配置项修改之后直接就生效了，建议修改配置后，给出个气泡提示操作成功，或者切换页面的时候，给出需要保存的提示信息。

**Comment by XPoet** [comment]
结果排查，没有发现你反馈的问题，重要操作（例如：删除）会有二次操作提示，其他的操作不需要
