### ISSUE TITLE
建议添加版本更新检测功能

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#226]
再次感谢作者 ❤️ 

联想到这个网站，在服务端版本高于浏览器本地缓存的时候，会弹出清空缓存并刷新的提示【<https://arkn.lolicon.app/#/hr>】，咱们是不是也可以加一个这个易用性提升呢？这样就可以避免好多人忘记强制刷新本地缓存的问题了。

> 不太会这个工具的开发，在什么地方可以找到相关的知识呢？想学习一下

**Comment by XPoet** [comment]
这个建议挺好，后续加上

**Comment by baboon-king** [comment]
@XPoet Please assign to me🥳
