### ISSUE TITLE
建议持久化配置信息

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#227]
目前看配置项是保存到了localstorage里，是否可以上传到仓库中呢？比如根目录下的`config.json`

当然更进一步的多配置，参考期望：#214

**Comment by XPoet** [comment]
这个建议挺好，后续加上

**Comment by XPoet** [comment]
该需求已实现，请退出登录，刷新页面之后，再使用。

<img width="983" alt="image" src="https://github.com/XPoet/picx/assets/24516169/fa9f3cc1-0193-4012-b20e-527d06bd508f">

<img width="880" alt="image" src="https://github.com/XPoet/picx/assets/24516169/18f912aa-71a9-4645-b5e8-c4c6aea534ff">
