### ISSUE TITLE
建议丰富图片压缩算法配置项

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#228]
目前的图片压缩配置项是这样的

![image](https://github.com/XPoet/picx/assets/29138871/15bfc51e-895c-4c42-80c8-ca85079e84f1)

是否可以添加【有损压缩/无损压缩】配置项，并对有损压缩添加【结构相似性】配置呢，如保留80%相似度？

**Comment by XPoet** [comment]
暂不支持其他方式的压缩，目前的压缩功能普遍反馈较好，短时间内不会有新的改变
