### ISSUE TITLE
建议水印新增原图功能

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#229]
比如我在配置里勾选了添加水印，同时我也想保留无水印的版本，一张图片上传两份，目前似乎无法达到这个目的。

```
xxx-watermark.webp
xxx-origin.webp
```

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/picx/assets/24516169/695e3176-1f08-4891-9a55-07e1b0bf63cb)

再次上传一份原图即可

可以在快捷操作那里快速关闭添加水印功能
