### ISSUE TITLE
能否在图片链接格式设置里添加BBCode代码格式

### ISSUE THREAD

**Issue by ke-xi** [XPoet/picx#233]
[img]URL[/img]就像这样的

**Comment by XPoet** [comment]
好的，下个版本加上

**Comment by ke-xi** [comment]
> 好的，下个版本加上

感谢

**Comment by XPoet** [comment]
PicX  https://picx.xpoet.cn  已发布 v2.3.4 ，该需求已添加，请清空浏览器缓存后使用。

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/picx/assets/24516169/5c6f8c4f-4798-4d89-957b-c22f9f3c8bf9)
