### ISSUE TITLE
能否在图床管理处加入区域选择功能

### ISSUE THREAD

**Issue by ke-xi** [XPoet/picx#234]
在选择多张图片时只有一个全选可用,否则就要一张一张的点选,非常麻烦,可以加入
<img width="1141" alt="Snipaste_2023-06-01_12-03-40" src="https://github.com/XPoet/picx/assets/58284266/d819ceff-dc1e-4cd7-a345-70c29058d8b5">
这样的框选,或则支持shift区域选择功能吗

**Comment by XPoet** [comment]
挺好的建议，后续版本加上

**Comment by XPoet** [comment]
PicX v3.0.0 已支持按住 shift 键选择图片，请使用最新版本。
