### ISSUE TITLE
能否加一个选项在上传时自动以上传时间命名

### ISSUE THREAD

**Issue by ke-xi** [XPoet/picx#236]
虽然加上哈希值可以避免重名,但是有些图片上传之前名字特别长,或者有特殊字符,那么导出的bbs格式链接就不能用了,还要手动重命名

用时间命名的话精确到秒,应该就不用担心重名的问题了,如果一秒内同时有两张照片的话,再加一个-1,-2,就没有这种问题了

**Comment by XPoet** [comment]
好的，后续版本加上该功能

**Comment by XPoet** [comment]
PicX `v2.3.6` 已发布，增加了时间戳命名功能。
进入 https://picx.xpoet.cn/ 刷新页面即可体验。

<img width="840" alt="image" src="https://github.com/XPoet/picx/assets/24516169/e79d0b60-5b81-4ff3-a278-b1fbee00e10a">

<img width="410" alt="image" src="https://github.com/XPoet/picx/assets/24516169/52593312-af1f-4484-91fc-669ca8940737">
