### ISSUE TITLE
Token窃取

### ISSUE THREAD

**Issue by WangQuan-cn** [XPoet/picx#237]
目前token是在localstorage中明文存储的，这样我获取到之后，可以将其投入到picgo中，直接增删改仓库内容。
这是否属于重大安全隐患？

可以使用非对称加密处理一下敏感信息
废弃当前所有的可能已泄露的token，并从localstorage中删除敏感信息
可能还需要发一个公告说明😥
如无法访问图片，可以用一个占位图片来通知上传者，让其重新生成token

**Comment by WangQuan-cn** [comment]
参考Eclipse的秘钥存储策略，即使是本人也不允许二次获取之前保存的token

**Comment by XPoet** [comment]
PicX 对 GitHub Token 没有本质上的关联，你的 GitHub Token 不是 PicX 帮你创建的，是你自己创建的，PicX 怎么可能来给你废弃掉之前的 Token ？？？请仔细理清他们之间的关系。
