### ISSUE TITLE
重新登录后，生成的外链都是undefined

### ISSUE THREAD

**Issue by AmineTsai** [XPoet/picx#24]
看了下是因为 management.vue 里面，写成了固定的字符串

github_url: generateExternalLink('github', item, this.userConfigInfo),
cdn_url: generateExternalLink('cdn', item, this.userConfigInfo),
markdown_gh: generateExternalLink('markdown_gh', item, this.userConfigInfo),
markdown_cdn: generateExternalLink('markdown_cdn', item, this.userConfigInfo),

应该是

github_url: generateExternalLink(ExternalLinkType.gh, item, this.userConfigInfo),
cdn_url: generateExternalLink(ExternalLinkType.cdn, item, this.userConfigInfo),
markdown_gh: generateExternalLink(ExternalLinkType.md_gh, item, this.userConfigInfo),
markdown_cdn: generateExternalLink(ExternalLinkType.md_cdn, item, this.userConfigInfo),

**Comment by XPoet** [comment]
@AmineTsai 
感谢反馈 ，Bug已修复，重新退出再登录即可
