### ISSUE TITLE
建议支持打包成客户端

### ISSUE THREAD

**Issue by zhouzongyan** [XPoet/picx#240]
像picgo打包成客户端以后，用户就能够有更快捷的操作，例如一键上传等，感谢作者

**Comment by XPoet** [comment]
有 PWA 版本，你可以安装试试。
![image](https://github.com/XPoet/picx/assets/24516169/4b980b03-94f8-4283-8efa-3d4306991d78)
![image](https://github.com/XPoet/picx/assets/24516169/d3ba8214-7d4c-4d32-9b9a-c52cfa22e1d1)

其他形式的客户端暂不考虑
