### ISSUE TITLE
请问如何部署？

### ISSUE THREAD

**Issue by geekqq** [XPoet/picx#244]
这个问题可能对程序员太简单了。但是我是小白，希望阁下能给一个简单的教程。我在自己的Ubuntu服务器上部署，使用了git clone仓库地址，然后npm install安装dependency，之后再build 就出错了，试了好几个服务器都是一样的错误。以下是error的内容：
![image](https://github.com/XPoet/picx/assets/53326015/bc211e54-71ab-4ba8-8374-b71272e066b2)

**Comment by XPoet** [comment]
不建议自己额外部署，直接使用 https://picx.xpoet.cn 即可，作者会持续更新维护。

**Comment by geekqq** [comment]
thanks 我在Vercel也部署成了，一键部署还是很方便的。自己折腾还是比较费劲的。多谢啦。
