### ISSUE TITLE
后续有可能发布cli版本吗?

### ISSUE THREAD

**Issue by CoderZuoHL** [XPoet/picx#246]
本人是一个typora使用者,
希望后续能有cli版本,通过node 命令上传图片

**Comment by XPoet** [comment]
后续版本考虑

**Comment by XPoet** [comment]
经过作者慎重分析和考虑，认为 PicX 不适合制作 CLI 版本，你在使用 Typora 过程中，可以先把图片上传，再复制链接到 Markdown 文件。
