### ISSUE TITLE
语言检测功能优化

### ISSUE THREAD

**Issue by 98zi** [XPoet/picx#249]
设置完简体中文后，每次刷新和打开网页都会再次弹窗，个人认为设置完逻辑上不应该再弹出，除非清理了本地缓存。

**Comment by XPoet** [comment]
你是不是开了 VPN 导致 IP 刷新一次就变化一次？

我在正常使用情况下没发现你提到的问题

**Comment by zishume** [comment]
> 你是不是开了 VPN 导致 IP 刷新一次就变化一次？
> 
> 我在正常使用情况下没发现你提到的问题

我的vpn线路是固定的，ip应该没有频繁变化。
