### ISSUE TITLE
希望支持仓库下的任意目录？

### ISSUE THREAD

**Issue by XuxuGood** [XPoet/picx#25]
现在只能选择一级目录，可否支持仓库下任意目录？
感谢作者大佬能把这个实现。
![image](https://user-images.githubusercontent.com/45960164/112707392-f42a4d00-8ee5-11eb-8339-1627d6607796.png)

**Comment by XPoet** [comment]
目前不支持，后续版本会增加这个功能

**Comment by XuxuGood** [comment]
期待期待，大佬调用Github OpenApi把这个给实现了。

**Comment by tramsky996** [comment]
同求！感谢大佬

**Comment by nerd010** [comment]
希望这个功能的优先级高一些，很需要。

当只是想要访问已存在的二级目录图片时，是没有办法直接查看的。
目前的解决方法：新建一个与原二级目录同名的目录，再上传一张图片，才可以访问在此目录下已存在的所有图片。

**Comment by XPoet** [comment]
@nerd010 
可以的，优先开发该功能

**Comment by XPoet** [comment]
PicX 已支持多级目录
![image](https://user-images.githubusercontent.com/24516169/147431219-8e36877a-efda-4c5c-8315-64e1f74c7063.png)
![image](https://user-images.githubusercontent.com/24516169/147431243-023b1eba-7c6a-477b-b5c7-0b02662e21c1.png)
![image](https://user-images.githubusercontent.com/24516169/147431261-bab87a2f-e943-4e12-b464-9866491cf956.png)
