### ISSUE TITLE
希望可以使用私有仓库

### ISSUE THREAD

**Issue by Febtw** [XPoet/picx#250]
目前 PicX 获取的仓库列表是公开仓库的列表，初始化创建的 picx-images-hosting 也是公开仓库。
虽然可以在配置好后在github将仓库改为私有，但那样会只剩下上传和浏览目录结构的功能；
图片管理中不显示缩略图；获取的链接缺少图片token，除非是github链接且在github账号登录的情况下，否则无法使用。

**Comment by picsstorage** [comment]
反代了GitHub之后，配置图片链接规则可以了，很赞的工具

**Comment by Febtw** [comment]
反代了GitHub之后，配置图片链接规则可以了，很赞的工具！！！
