### ISSUE TITLE
今天突然所有图片都无法显示了

### ISSUE THREAD

**Issue by Justice996** [XPoet/picx#251]
![image](https://github.com/XPoet/picx/assets/27287643/0ca9a522-51e1-4e8e-ac2f-731ff4c2f92f)

**Comment by hikyuu** [comment]
#154 #

**Comment by blage-coding** [comment]
+1，又得换CDN了

**Comment by XPoet** [comment]
作者正在进行紧急更新

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/picx/assets/24516169/b1bca090-da04-4964-951c-c3c124ac7861)

PicX 已更新 statically 图片链接规则，请退出登录之后，重新配置图片使用。

**Comment by Justice996** [comment]
> picx.xpoet.cn

没有找到退出登录按钮，直接重置图床配置再登录后没效果，清掉localstorage后再次配置才生效

**Comment by XPoet** [comment]
点击右上角的头像，可弹出下拉框，有 “退出登录” 选项。

![image](https://github.com/XPoet/picx/assets/24516169/0ca9a062-a357-4a1c-a7ac-007357e40314)


直接清除 localStorage 也是可以的

**Comment by Justice996** [comment]
> 点击右上角的头像，可弹出下拉框，有 “退出登录” 选项。
> 
> ![image](https://user-images.githubusercontent.com/24516169/268569882-0ca9a062-a357-4a1c-a7ac-007357e40314.png)
> 
> 直接清除 localStorage 也是可以的

![image](https://github.com/XPoet/picx/assets/27287643/0264ef9a-9023-4ffe-acb9-bd4d2f8ac5a4)
新bug 我这确实是登录

**Comment by Justice996** [comment]
> 点击右上角的头像，可弹出下拉框，有 “退出登录” 选项。
> 
> ![image](https://user-images.githubusercontent.com/24516169/268569882-0ca9a062-a357-4a1c-a7ac-007357e40314.png)
> 
> 直接清除 localStorage 也是可以的

![image](https://github.com/XPoet/picx/assets/27287643/30d43f01-fe80-4bd2-b028-1d498b1abfa0)
我自己请求了一下 发现我的名字是null，离谱

**Comment by L1Chenxv** [comment]
更新了之后，网页上还是加载不出来图片

**Comment by Justice996** [comment]
> 更新了之后，网页上还是加载不出来图片

貌似大陆不能访问了

**Comment by NovaShen555** [comment]
不行，原有图片链接仍然无法访问，现在是原有博客的图片全面瘫痪
我可不想一个个替换链接

**Comment by hfshaobing** [comment]
你们能用了吗，我的重新登录，重新配了还是无法加载

**Comment by NovaShen555** [comment]
> 你们能用了吗，我的重新登录，重新配了还是无法加载

只能更换cdn使用，原来默认那个应该是完全寄了

**Comment by Justice996** [comment]
被墙了,国内确实访问不了了，挂梯子正常

**Comment by Salmonberry** [comment]
我按照楼上说的，退出重新登陆，也是不行。然后全局替换替换为其他CDN就好了。这里的对CDN的依赖太强了，觉得应该可以弄一个应用层的url，通过接口链接底层的CDN，这样即使随意切换CDN也不会影响已经暴露出去使用的url

**Comment by NovaShen555** [comment]
> 我按照楼上说的，退出重新登陆，也是不行。然后全局替换替换为其他CDN就好了。这里的对CDN的依赖太强了，觉得应该可以弄一个应用层的url，通过接口链接底层的CDN，这样即使随意切换CDN也不会影响已经暴露出去使用的url

是的，您提个issue吧，看看作者怎么说

**Comment by 98zi** [comment]
> 我按照楼上说的，退出重新登陆，也是不行。但全局替换替换为其他CDN就好了。这里的对CDN的依赖太强了，觉得应该可以弄一个应用层的url，通过接口链接底层的CDN，这样即使随意切换CDN也不会影响已经暴露出去使用的url

这就需要开发者自己维护一套cdn程序了，需要成本。

我是用netlify做cdn，速度很快，而且更换也不麻烦，只需要批量替换前缀就行了，后面的path基本都是固定的。

**Comment by Salmonberry** [comment]
> > 我按照楼上说的，退出重新登陆，也是不行。但全局替换替换为其他CDN就好了。这里的对CDN的依赖太强了，觉得应该可以弄一个应用层的url，通过接口链接底层的CDN，这样即使随意切换CDN也不会影响已经暴露出去使用的url
> 
> 这就需要开发者自己维护一套cdn程序了，需要成本。
> 
> 我是用netlify做cdn，速度很快，而且更换也不麻烦，只需要批量替换前缀就行了，后面的path基本都是固定的。

明白你的意思，谢谢

**Comment by DonTequilaaa** [comment]
目前还是无法正常使用，退出登陆、换token都无法解决

**Comment by Timacoldplay** [comment]
直接寄了

**Comment by XPoet** [comment]
各位请看这里
#261

**Comment by dhay3** [comment]
如果文件比较多，直接用脚本改方便多了，改成 github  的一劳永逸  :laughing:  

```python
import re
import os

owner = ''
repo = ''
branch = ''
github = f'github.com/{owner}/{repo}/raw/{branch}'
staticaly = f'cdn.staticaly.com/gh/{owner}/{repo}@{branch}'
chinaJsDelivr = f'jsd.cdn.zzko.cn/gh/{owner}/{repo}@{branch}'
jsDelivr = f'cdn.jsdelivr.net/gh/{owner}/{repo}@{branch}'
basepath = ''


def redistribution(basepath):
    for root, dirs, files in os.walk(basepath):
        for file in files:
            if file and os.path.splitext(file)[1] == '.md':
                filename = os.path.join(root, file)
                with open(filename) as f:
                    d = re.sub(f'{staticaly}', f'{github}', f.read())
                    d = re.sub(f'{chinaJsDelivr}', f'{github}', d)
                    d = re.sub(f'{jsDelivr}', f'{github}', d)
                with open(filename, 'w') as f:
                    f.write(d)


if __name__ == '__main__':
    redistribution(basepath)

```
