### ISSUE TITLE
打包一个本地chrome扩展

### ISSUE THREAD

**Issue by 98zi** [XPoet/picx#259]
😁

**Comment by 98zi** [comment]
打包一个本地chrome扩展。[chrome-picx.zip](https://github.com/XPoet/picx/files/12679509/chrome-picx.zip)

![image](https://github.com/XPoet/picx/assets/65840178/6baaeb5c-259f-41ac-aa95-adf96ddc3f5c)

**Comment by XPoet** [comment]
PicX 还在不断迭代中，近期有新版本发布。我有账号，由我来上架插件市场，也方便后续维护。

**Comment by 98zi** [comment]
> PicX 还在不断迭代中，近期有新版本发布。我有账号，由我来上架插件市场，也方便后续维护。

好的感谢

**Comment by shenweiyan** [comment]
所以，请问一下，什么时候上架插件市场？

**Comment by XPoet** [comment]
PicX 决定不上架 Chrome 插件市场，增加使用门槛和维护成本，网页在线使用就很方便，即开即用，可以把网址收藏起来，也可以安装  PicX 的 PWA 程序。
