### ISSUE TITLE
怎么批量上传呀

### ISSUE THREAD

**Issue by sunl888** [XPoet/picx#26]
官网好像不能批量上传吧  [上传](https://picx.xpoet.cn/#/upload)

**Comment by XPoet** [comment]
可以批量上传，你得先

- 选择多张图片
- 拖拽多张图片
- 粘贴多张图片

到上传区域，然后点击上传

![image](https://user-images.githubusercontent.com/24516169/113812989-9e855880-97a1-11eb-82a2-8fe7c6f71d71.png)

**Comment by sunl888** [comment]
> 可以批量上传，你得先
> 
> * 选择多张图片
> * 拖拽多张图片
> * 粘贴多张图片
> 
> 到上传区域，然后点击上传
> 
> ![image](https://user-images.githubusercontent.com/24516169/113812989-9e855880-97a1-11eb-82a2-8fe7c6f71d71.png)

好的，谢谢哈
