### ISSUE TITLE
[feat request] 能否为当前CDN管理系统上添加一层公开的URL，从而避免因直接引用某特定CDN不可用，而造成的大范围修改url引用的问题

### ISSUE THREAD

**Issue by Salmonberry** [XPoet/picx#260]

**Comment by xingpingcn** [comment]
那难道你要手动复制一遍然后再替换吗？为什么不用正则替换呢？

**Comment by XPoet** [comment]
可以使用编辑器的全局替换功能，请看这里 #261

**Comment by XPoet** [comment]
该需求暂不考虑开发，对作者来说成本巨大。

实际上，通过 PicX 上传的图片，存储在 GitHub 仓库里，只要 GitHub 不倒闭，图片资源会一直存在，有经济能力的朋友可以自己搭建服务器来代理 GitHub 资源，或者使用免费的 [CloudFlare](https://www.cloudflare.com/)，之后在 `我的设置 - 图片链接规则配置`，添加自己的自定义图片链接规则。

PicX `v2.4.0 ` 已发布，增加一键部署到 GitHub  Pages 功能，即可获取  GitHub  Pages 托管静态图片资源的访问能力，该方式相对最为稳定，中国大陆地区访问速度也还行。

<img width="970" alt="image" src="https://github.com/XPoet/picx/assets/24516169/7cec6b7d-070e-418f-9434-916d170ebc6d">

PicX 入口 >> https://picx.xpoet.cn
