### ISSUE TITLE
📢 必读公告

### ISSUE THREAD

**Issue by XPoet** [XPoet/picx#261]
1. PicX 原来的默认图片链接规则 **Staticaly** `https://cdn.staticaly.com` 已经无法使用。
2. 新的默认图片链接规则更新为 **Statically** `https://cdn.statically.io`，但是在中国大陆地区无法使用，需要 FQ。
3. PicX 目前内置的 `Statically`、`jsDelivr`、`GitHub` 这三种图片链接规则，均需要 FQ 才能访问。
4. 如你需要在中国大陆访问图片，请前往 **我的设置 / 图片链接规则配置**，手动切换链接规则为 `ChinaJsDelivr`。
5. 借助编辑器全局替换功能，可快速批量修改图片链接：
   - `https://cdn.staticaly.com/gh/` -> `https://cdn.statically.io/gh/`   （需要翻墙访问）
   - `https://cdn.staticaly.com/gh/` -> `https://jsd.cdn.zzko.cn/gh/`   （无需翻墙访问）
6. 你也可以在 **我的设置 / 图片链接规则配置** 中，配置自定义的图片链接规则，然后使用你自己的规则。
7. 作者正在积极探索更好友好且稳定的图片链接生成方式，敬请期待新版本上线。

<img width="1208" alt="image" src="https://github.com/XPoet/picx/assets/24516169/da9f3a5d-4667-4d1f-91e0-a92ed082b004">

**Comment by dhay3** [comment]
如果文件比较多，直接用脚本改方便多了，改成 github  的一劳永逸  :laughing:  

```python
import re
import os

owner = ''
repo = ''
branch = ''
github = f'github.com/{owner}/{repo}/raw/{branch}'
staticaly = f'cdn.staticaly.com/gh/{owner}/{repo}@{branch}'
chinaJsDelivr = f'jsd.cdn.zzko.cn/gh/{owner}/{repo}@{branch}'
jsDelivr = f'cdn.jsdelivr.net/gh/{owner}/{repo}@{branch}'
basepath = ''


def redistribution(basepath):
    for root, dirs, files in os.walk(basepath):
        for file in files:
            if file and os.path.splitext(file)[-1] == '.md':
                filename = os.path.join(root, file)
                with open(filename) as f:
                    d = re.sub(f'{staticaly}', f'{github}', f.read())
                    d = re.sub(f'{chinaJsDelivr}', f'{github}', d)
                    d = re.sub(f'{jsDelivr}', f'{github}', d)
                with open(filename, 'w') as f:
                    f.write(d)


if __name__ == '__main__':
    redistribution(basepath)

```

**Comment by C2yb8er** [comment]
已解决图片失效的问题，给作者点个赞！

**Comment by XPoet** [comment]
jsDelivr 规则的图片链接，在中国大陆可以访问了，无需 FQ

**Comment by cmty256** [comment]
为啥更换链接之后，部署dist之后图片都打不开了？在本地typora是可以看到图片的。

**Comment by XPoet** [comment]
> 为啥更换链接之后，部署dist之后图片都打不开了？在本地typora是可以看到图片的。

@cmty256 
没看明白，请描述清楚，并附带截图。你原来用的是哪中图片链接规则，更换成哪种？

**Comment by cmty256** [comment]
> > 为啥更换链接之后，部署dist之后图片都打不开了？在本地typora是可以看到图片的。
> 
> @cmty256 没看明白，请描述清楚，并附带截图。你原来用的是哪中图片链接规则，更换成哪种？

就我把那三种链接规则都换成了ChinaJsDelivr，然后部署项目github page之后浏览器打开网站就看不到图片了，但是我本地的md文件是可以看到图片的。
![image](https://github.com/XPoet/picx/assets/82518321/ab12ba7f-b5de-4812-ba6f-93e5df6578e5)
![image](https://github.com/XPoet/picx/assets/82518321/646c9d33-869b-4fd8-a82c-bd5a94d280d9)

**Comment by XPoet** [comment]
这种情况作者也不清楚，正常来说，你的图片链接能不能正常访问，只跟你网络环境有关。
建议你把图床部署到 GitHub Pages，然后把图片链接规则替换成 GitHub Pages

**Comment by XPoet** [comment]
@cmty256 
另外，遇到问题，不要在此 Issue 评论，请新开 Issue。
