### ISSUE TITLE
图床管理页面无法预览图片，显示加载失败

### ISSUE THREAD

**Issue by Orange5722** [XPoet/picx#269]
如图，复制图片链接后可以正常访问，但是在图床管理页的图片都显示加载失败，且刷新无用，故来求助😭
<img width="1582" alt="image" src="https://github.com/XPoet/picx/assets/73053146/e4ec014f-a030-458e-8047-6c6f2628d656">

**Comment by Orange5722** [comment]
现在又好了，不稳定可能是什么原因呢🤔

**Comment by Salmonberry** [comment]
> 现在又好了，不稳定可能是什么原因呢🤔

我觉得这应该是一个bug，我昨晚到现在都是这样子显示不出来。
过了一段时间再登登，点击**图床管理页**的刷新按钮进行刷新还弹了一个toast出来是`AxiosError: Network Error`。下面是在`Console`中具体报出的错误：
```
vendor.73ea3ad4.js:1 TypeError: Cannot destructure property 'rule' of 't.imageLinkType.presetList[l]' as it is undefined.
    at Va (index.c5bd3aad.js:1:32361)
    at Ae.fn (index.c5bd3aad.js:1:79695)
    at Ae.run (vendor.73ea3ad4.js:1:5505)
    at get value [as value] (vendor.73ea3ad4.js:1:14368)
    at Proxy.<anonymous> (index.c5bd3aad.js:1:82767)
    at Fn (vendor.73ea3ad4.js:1:17733)
    at Ae.fn (vendor.73ea3ad4.js:3:21731)
    at Ae.run (vendor.73ea3ad4.js:1:5505)
    at P.e.update (vendor.73ea3ad4.js:3:21982)
    at P (vendor.73ea3ad4.js:3:22008)
(anonymous) @ vendor.73ea3ad4.js:1
```

**Comment by XPoet** [comment]
这不是 bug，也不属于 PicX 本身的问题。使用 ChinaJsDelivr 规则访问图片资源有点异常，各位小伙伴请切换至 GitHub Pages 吧，是目前最稳定的。

1、将图床一键部署到 GitHub Pages

<img width="1167" alt="image" src="https://github.com/XPoet/picx/assets/24516169/12841a6d-4d86-47c8-9258-86f877789ccb">


2、把图片链接规则切换到 GitHub Pages
<img width="1128" alt="image" src="https://github.com/XPoet/picx/assets/24516169/53427156-d14a-4e48-b0f5-a848e4edd2d3">

注意：所有图片上传完成后，需手动点击一下部署到 GitHub Pages

**Comment by XPoet** [comment]
> 谢谢大佬指点，还有两个个问题哈： 1.我注意到每次新上传的图片在部署之前在管理界面仍然无法正常预览，是每次上传新的图片之后都需要重新部署才能生效吗 2.我发现每次部署完都需要稍等一两分钟才能正常预览，所以部署完之后是有需要等待生效的时间吗 再次谢谢大佬的回复，被之前jsd的cdn污染问题弄怕了🥹

A1、每次上传了新图片，必须再次 GitHub Pages 部署成功 之后，图片链接才能生效。但是，完全没必要上传一张图片，就点击一次部署，你可以等所有图片都上传完成后，再部署。
A2、GitHub Pages 服务部署成功之后，图片链接就能访问，生效时间取决于 GitHub Pages 服务的部署时间，没有固定的。

> 如果你在有梯子的网络环境下，使用 jsDelivr、Statically 等规则，上传完成就能预览。
