### ISSUE TITLE
登陆后不能显示账号下所有仓库

### ISSUE THREAD

**Issue by sprindjack** [XPoet/picx#27]
登陆账号后，只能显示5个仓库，也不知道是不是随机的。其他仓库包括新建仓库都不能显示。

**Comment by XPoet** [comment]
怎么会呢？使用 token 登录后，获取到的所有自己建的仓库（过滤掉了 fork 别人的仓库），你要先建好仓库，在使用 token 登录获取

**Comment by XPoet** [comment]
你退出，再重新登录获取看看，或者把浏览器缓存清空，再看看

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/114270154-64d07e00-9a3d-11eb-8e72-b96b9a304408.png)

**Comment by sprindjack** [comment]
已退出重试了。
Token按教程给予repo权限。
在多个浏览器浏览器隐身模式也测试过了：iOS：Chrome、Safari、Alook，安卓：Chrome、Firefox
不知道是不是我的仓库太多了。
![Imgur](https://i.imgur.com/B9JjRq8.jpg)

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/114270704-6fd8dd80-9a40-11eb-98ae-01a24449e1f5.png)

你是平板打开 PicX 的吗？看看仓库列表里有没有滚动条

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/114270789-d827bf00-9a40-11eb-9ec1-af78f33e332d.png)

我zhang'h账号里几十个仓库都能显示

**Comment by XPoet** [comment]
你是用平板打开 PicX 网站的吗？看看仓库列表那里有没有滚动条，滑动一下

**Comment by sprindjack** [comment]
我又重新配置了一次。用平板及手机均是这个问题，并没有下拉条。
新建了github小号来放图片，问题解决😭。

**Comment by XPoet** [comment]
你用电脑登录试试看
这种情况还是第一次听说，是不是对你的 GitHub 账号设了一些限制

**Comment by sprindjack** [comment]
试了下windows 10 edge浏览器，也是这样。大概是我账户有问题，但我应该没设置过什么限制的。

**Comment by i0Ek3** [comment]
我这边也是同样的问题，没办法显示全部的repo，下拉列表只能显示到f开头的目录，后将项目改名为axxxx，就能在前面显示了。
