### ISSUE TITLE
图床管理图片都是空白

### ISSUE THREAD

**Issue by skylimiter** [XPoet/picx#271]
![image.png](https://p.sda1.dev/14/34253084733c404e81ce068b8d174905/image.png)
确定上传成功无误
跳到图床管理的页面，呈现空白
![image.png](https://p.sda1.dev/14/19ea92ef0a4355cbb41278dadb73bdba/image.png)
GitHub Pages 有部署成功

**Comment by mas-alone** [comment]
我也遇到过这个情况，试着清理缓存试一下？
我是用Private模式进去后就可以访问到了。

**Comment by skylimiter** [comment]
谢谢，已解决
然后离题一下
使用GitHub Pages后，点击该图片连接，却显示不出图片
[![image.png](https://i.postimg.cc/9QjPspKs/image.png)](https://postimg.cc/dL4Ty8q9)

**Comment by XPoet** [comment]
使用 GitHub Pages 图片规则的链接，必须先部署到 GitHub Pages 服务，否则无效。

![image](https://github.com/XPoet/picx/assets/24516169/d247dde5-6b0c-47e1-8e03-b433302708f9)

**Comment by CMER-SZ** [comment]
在inprivate模式  可以，  在清除页面缓存和数据的时候也可以

**Comment by skylimiter** [comment]
发现利用GitHub Pages规则，就会有机率发生需要清除页面缓存和数据，才能显示图床管理内的图片
目前先不用GitHub Pages后，这问题就没有发生过

**Comment by yixuan66** [comment]
大哥，咋解决的，
![Uploading Screenshot_20231216_165150.jpg…]()

**Comment by skylimiter** [comment]
清除页面所有cookie与缓存就可以了，然后重新图床部署一次即可
后续我没有使用GitHub Pages规则，就不曾出现这类问题，到现在问题也没有反覆发生

谢谢大家帮忙，先close了
