### ISSUE TITLE
复制图片按钮没有反应

### ISSUE THREAD

**Issue by xustudyxu** [XPoet/picx#274]
![image](https://github.com/XPoet/picx/assets/53399655/0e8fe2af-ad9b-409e-904a-7c7de722e46b)
点击没有反应

**Comment by XPoet** [comment]
复制功能是正常可用的。
请检查一下你的浏览器是否禁用了代码复制功能。
解决方法网上搜一下就有了。

**Comment by xustudyxu** [comment]
好的 谢谢大佬

**Comment by xustudyxu** [comment]
> 复制功能是正常可用的。 请检查一下你的浏览器是否禁用了代码复制功能。 解决方法网上搜一下就有了。

好的 谢谢大佬
