### ISSUE TITLE
点击“复制图片链接”无法复制，刷新目录提示 Code: 401, Message: Bad credentials

### ISSUE THREAD

**Issue by SinzMise** [XPoet/picx#277]
![image](https://github.com/XPoet/picx/assets/120767492/98c4e0af-839e-4b52-9689-7054f0969bfd)

**Comment by M-500** [comment]
同样的问题，至今仍然无法复制图片链接

**Comment by XPoet** [comment]
你们的 Token 可能已过期，或者权限不够，请[重新生成新 Token 并使用新 Token 登录](https://picx-docs.xpoet.cn/docs/usage-guide/config.html#%E5%A1%AB%E5%86%99-github-token-%E7%99%BB%E5%BD%95)，或 [OAuth 授权 登录](https://picx-docs.xpoet.cn/docs/usage-guide/config.html#github-oauth-%E6%8E%88%E6%9D%83%E7%99%BB%E5%BD%95)。

**Comment by M-500** [comment]
刚才测试了，通过OAuth授权方式重新登录没问题，感谢作者大大
