### ISSUE TITLE
点击图片链接没法复制，f12控制台提示Cannot destructure property 'rule' of 'a.imageLinkType.presetList[i]' as it is undefined.

### ISSUE THREAD

**Issue by SinzMise** [XPoet/picx#279]
之前的401错误，重登确实好了，能上传图片但复制提示这个：
![msedge_nKehpAan7M](https://github.com/XPoet/picx/assets/120767492/b90501ef-a73f-417d-89ba-c4a5fa419f8d)

**Comment by XPoet** [comment]
无法复现你的问题，是你的旧的缓存数据导致的,请退出登录，刷新下页面，之后重新登录即可

**Comment by ysdxz207** [comment]
我也遇到了这个问题，第一次登录就遇到了；退出重新登录还是一样，另外新增了自定义的图片链接规则之后，同步到云端仓库成功，刷新页面后新增的图片链接规则没了。

**Comment by XPoet** [comment]
请退出登录，刷新下页面，之后重新登录即可。
如果还存在这个问题，就是你的浏览器缓存导致，请清一下浏览器缓存。
