### ISSUE TITLE
❤️ 欢迎小伙伴们加入微信交流群~  ✿✿ヽ(°▽°)ノ✿

### ISSUE THREAD

**Issue by XPoet** [XPoet/picx#28]
因群成员大于 200 人，需要关注公众号《前端鼓励师》，添加作者微信，再由作者拉你进群~

![FEC-Card](https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/FE-Cheerleaders/FEC-Card.76dbi8n1bkk0.png)

**Comment by XPoet** [comment]
关于PicX 图床的任何问题和前端技术问题，都可以在群里提问，作者会积极为大家解答，同时，群里会经常分享学习干货、视频教程、面试指南等，也会经常给大家发红包，欢迎加入~━(*｀∀´*)ノ亻! 🌹🌹🌹

**Comment by public-cdn** [comment]
我可以自己搭建这个picx 吗

**Comment by XPoet** [comment]
@public-cdn 
可以，但不建议。直接用 PicX 官网就好了，作者会一直更新维护

**Comment by Somnus711** [comment]
> 我是按照流程生产的token，然后一直出现 401的错误

请问这个问题现在解决了吗 我也遇到了一样的问题

**Comment by XPoet** [comment]
@Somnus711 
请使用最新版本 Chrome 或 Edge 浏览器 。
或提供下你们使用 PicX 的操作系统、浏览器及浏览器版本、方便排查。

**Comment by AlpacaMe** [comment]
> > 我是按照流程生产的token，然后一直出现 401的错误
> 
> 请问这个问题现在解决了吗 我也遇到了一样的问题

我换个浏览器就好了，你试试是不是VPN的问题，我之前就是因为挂了VPN认证失败

**Comment by Somnus711** [comment]
> > > 我是按照流程生产的token，然后一直出现 401的错误
> > 
> > 
> > 请问这个问题现在解决了吗 我也遇到了一样的问题
> 
> 我换个浏览器就好了，你试试是不是VPN的问题，我之前就是因为挂了VPN认证失败

嗯嗯 谢谢提醒 换了火狐浏览器就正常登录了 之前用chrome挂了vpn也登录不了

**Comment by Eden-Lin** [comment]
我能把你的代码打包成docker镜像么？我想在自己的nas上的docker上搭建这套服务

**Comment by M-cheng-web** [comment]
> > > > 我是按照流程生产的token，然后一直出现 401的错误
> > > 
> > > 
> > > 请问这个问题现在解决了吗 我也遇到了一样的问题
> > 
> > 
> > 我换个浏览器就好了，你试试是不是VPN的问题，我之前就是因为挂了VPN认证失败
> 
> 嗯嗯 谢谢提醒 换了火狐浏览器就正常登录了 之前用chrome挂了vpn也登录不了

我也是换了个浏览器就正常了，奇怪

**Comment by ziyuanzhp** [comment]
建议添加一个图片链接转化为html代码，真的很需要

**Comment by XPoet** [comment]
> 建议添加一个图片链接转化为html代码，真的很需要

@ziyuanzhp 后续会支持，另外新需求问题，请新开 Issue，要不然容易忽略

**Comment by xiaozhang959** [comment]
请问作者这个插件是从utools下架了嘛 ？
