### ISSUE TITLE
图片上传后，复制不了图片链接

### ISSUE THREAD

**Issue by JIALIKEMENG** [XPoet/picx#283]
图片正常上传了，但是无论是点击复制图片链接还是右键复制链接，都获取不了图片链接网址，而是获取了data:image/webp;base64,UklGRubWCgBXRUJQVlA4I……字符串。是我哪里设置错误吗？
![Snipaste_2024-02-01_16-47-28](https://github.com/XPoet/picx/assets/114821530/49d24623-e55c-4c09-a167-24498bdd2661)
![Snipaste_2024-02-01_16-47-50](https://github.com/XPoet/picx/assets/114821530/bdde3ac3-e8d9-4feb-a05f-bcc0b269f769)
![Snipaste_2024-02-01_16-48-08](https://github.com/XPoet/picx/assets/114821530/8c99581f-d364-4489-b1d6-e6edd0dcf841)

**Comment by XPoet** [comment]
1、点击 “复制图片链接” 按钮，如果无法复制，请检查一下你的浏览器是否禁用了复制功能。

<img width="212" alt="image" src="https://github.com/XPoet/picx/assets/24516169/321dd464-5c8e-4f92-8dc2-fce321efb091">

2、在 “上传图片” 页面，已上传列表显示的是图片的 base64 编码，不应该使用浏览器自带的右键复制。
3、正常情况是你上传图片后会自动复制图片链接

**Comment by JIALIKEMENG** [comment]
感谢回复告知。常用浏览器安装的扩展和脚本较多，可能有冲突影响（但并未禁止复制），换了另一个比较干净的浏览器OK了，而且，在jsDelivr链接规则下不用魔法图片可正常显示。
感谢你的付出，顺祝新年快乐，身体健康，万事顺遂！

**Comment by dhay3** [comment]
同样复制不了。看了一下对应的图床，文件已经上传了。但是好像不是插件的原因，我把插件都关闭了，换浏览器也不行。看了一下控制台，有错误日志。

![image](https://github.com/XPoet/picx/assets/62749885/a2d34a20-660b-48ff-85f6-cefeffc00815)

错误如下
```
vendor.2c125885.js:12 TypeError: Cannot destructure property 'rule' of 'a.imageLinkType.presetList[i]' as it is undefined.
    at ma (index.5202537e.js:1:38245)
    at ha (index.5202537e.js:1:38889)
    at e.imgObj.uploadStatus.progress.o.onClick.a.<computed>.a.<computed> (index.5202537e.js:1:68655)
    at un (vendor.2c125885.js:12:13091)
    at cn (vendor.2c125885.js:12:13169)
    at HTMLDivElement.n (vendor.2c125885.js:14:45707)
(anonymous) @ vendor.2c125885.js:12
fn @ vendor.2c125885.js:12
un @ vendor.2c125885.js:12
cn @ vendor.2c125885.js:12
n @ vendor.2c125885.js:14
```

对前端不是特别了解，但是尝试 Debug 了一下，对应的取值是逻辑上好像确实是 undefined
![image](https://github.com/XPoet/picx/assets/62749885/0808487d-d8be-4353-8c51-34d07b0cfbe4)

**Comment by XPoet** [comment]
@dhay3 
无法复现你的问题，请确保你的代码是 master 分支最新的。

**Comment by dhay3** [comment]
@XPoet 不好意思，应该是我自己的问题，麻烦了。在浏览正常模式下我关掉所有的插件不行，但是换成无痕模式的就可以了，我自己排查看看。

**Comment by Reid00** [comment]
@dhay3  请问你怎么解决的这个问题，我目前也有这个问题

**Comment by dhay3** [comment]
@Reid00 不确定你的问题是否和我的相同，我的是把站点对应的 Cookies 清空就可以了

**Comment by Reid00** [comment]
@dhay3  感谢，不过貌似还是不起作用。edge 这个不知道什么情况
