### ISSUE TITLE
在图床管理中双击打开图片无响应

### ISSUE THREAD

**Issue by imageHostXX** [XPoet/picx#284]
chrome 版本 121.0.6167.140
退出登录，清理缓存都试过，一样无响应
错误代码：Out of Memory

**Comment by XPoet** [comment]
不太清楚你反应的问题，录个屏我看下

**Comment by shaobingtongzhi** [comment]
一样的问题，不能上传，不能放大查看，chrome 版本：121.0.6167.139; macbook版本：big sur 11.2.3

**Comment by XPoet** [comment]
该问题已在 v3.0.0 得到优化，请使用最新版本。
详情请看必读公告 #287
