### ISSUE TITLE
建议上传时重命名直接用哈希值以及日期目录可以自定义

### ISSUE THREAD

**Issue by MH50382** [XPoet/picx#289]
1. 直接在文件名后加哈希值，风格不够统一，看起来很混乱。建议上传时直接用哈希值重命名。

2. 日期目录精准到天导致长期使用创建文件夹太多。建议以年/月两级目录划分，如年文件夹下根据上传时间自动创建（或移动到）对应月文件夹；或者直接创建YY-MM格式文件夹。

**Comment by XPoet** [comment]
A1：很多人都是需要保留文件名的，方便查看文件和筛选。
A2：可以用手动创建目录来规避这个问题。
<img width="710" alt="image" src="https://github.com/XPoet/picx/assets/24516169/7a72c44c-f161-40f3-850c-fff51fb531e6">
