### ISSUE TITLE
建议开启链接批量复制

### ISSUE THREAD

**Issue by wxydejoy** [XPoet/picx#29]
一个个复制也太累了

**Comment by XPoet** [comment]
@wxydejoy 
可以用，后续版本把这个需求加上去，敬请关注

**Comment by XPoet** [comment]
@iwlei 
BBCode 格式不清楚，麻烦给个示例

**Comment by iwlei** [comment]
> @iwlei BBCode 格式不清楚，麻烦给个示例

[img]图片链接[/img]

即img把链接夹住

**Comment by XPoet** [comment]
PicX 已支持批量复制链接功能
![image](https://user-images.githubusercontent.com/24516169/147431420-af3eb254-df11-405f-978d-38a9e226b411.png)
