### ISSUE TITLE
“在线使用入口”支持自行部署吗？

### ISSUE THREAD

**Issue by JavaZeroo** [XPoet/picx#295]
rt，翻了一下文档没有看到相关内容

**Comment by XPoet** [comment]
- 你可以去自行部署，不提供部署教程
- PicX 本身处于持续的维护和迭代中，不断有旧 Bug 修复和新功能增加，作者本人极其不建议用户额外自行部署一套 PicX 站点，直接使用官方网站 https://picx.xpoet.cn/ 即可，有任何问题作者都会及时发版更新，省心、省事、省时。
- 对于用户自行部署 PicX 产生的一切问题，作者不会给予解答。PicX 代码是百分百开源的，丝毫不用担心数据安全，完全没有额外自行部署的必要。
