### ISSUE TITLE
不能一次上传多张图片就很难受啊

### ISSUE THREAD

**Issue by QIXQI** [XPoet/picx#3]

**Comment by XPoet** [comment]
批量上传功能，很好的建议👍 
我尽快搞起来

**Comment by Yakumo-Yukari** [comment]
还是没有添加批量上传吗？如果图片比较多一张一张传有点难受 重复同样的操作太折磨人了

**Comment by XPoet** [comment]
@Yakumo-Yukari 
此功能准备开发中...

**Comment by XPoet** [comment]
PicX 图片批量上传功能已实现，大家来尝鲜吧，这个需求拖太久了 ┭┮﹏┭┮
