### ISSUE TITLE
复制图片链接没反应！！！！！

### ISSUE THREAD

**Issue by MingTu01** [XPoet/picx#309]
![1714900035507](https://github.com/XPoet/picx/assets/121942049/bf3ba5fb-3100-48dd-9810-e7e5556aa1b6)
正常上传，并且部署到GitHub Pages的图片。点击复制链接没有任何反应。

**Comment by amiaoapp** [comment]
咋解决的？

**Comment by XPoet** [comment]
请检查你的浏览器是不是禁止复制了吗？？？？？
