### ISSUE TITLE
建议添加图片水印功能

### ISSUE THREAD

**Issue by WhyWhatHow** [XPoet/picx#31]
图片水印可以弄得简单一点, 比如固定位置(图片右下角), 然后+文字版权信息就好...
不知道可不可以????

**Comment by XPoet** [comment]
挺好的建议，等我有空研究一下

**Comment by WhyWhatHow** [comment]
> 挺好的建议，等我有空研究一下

这个是我在用hexo 搭建博客用的一个图片水印方式, 不知道对您有没有用处,link我在下面给出来了.
[用nodeJs 图片添加水印](https://blog.jijian.link/2020-04-17/nodejs-watermark/)
最后,谢谢你提供如此好用的图床!

**Comment by XPoet** [comment]
好勒，多谢，抽空研究下，这个实现难度可能比较大 ￣□￣｜｜

**Comment by JakeWoki** [comment]
https://github.com/huxiaocheng/vue-gn-components
水印参考这个项目
