### ISSUE TITLE
这个可以我自行部署吗

### ISSUE THREAD

**Issue by woshichenghaibo** [XPoet/picx#312]
还是只能用你自己的服务器_？
万一哪天你的域名出问题了，图片怎么能链接？

**Comment by XPoet** [comment]
图片存储在你自己的 GitHub 仓库，除非 GitHub 倒了，否则图片一直存在。
不建议自行部署。
详情查看文档：https://picx-docs.xpoet.cn/docs/user-notice/Q&A.html#q-%E5%A6%82%E4%BD%95%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2-picx
