### ISSUE TITLE
图片文件列表加载时间过长

### ISSUE THREAD

**Issue by cnbilinyj** [XPoet/picx#315]
文件夹列表已经加载完成后，仍需等待30秒以上才能加载出图片文件列表

https://github.com/XPoet/picx/assets/99505726/0ff4fc4e-1bb3-4a85-ae2e-76e5fb6237b1

**Comment by wmxzrs** [comment]
用的chrome,同样的问题，并且加载不出来。

**Comment by XPoet** [comment]
图片资源存储在GitHub 服务器，可能是你的网络问题

**Comment by XPoet** [comment]
偶尔会有这种现象，紧急时搭把梯子
