### ISSUE TITLE
希望在自定义链接中新增自动增加版本号

### ISSUE THREAD

**Issue by Aixbox** [XPoet/picx#318]
大佬能否在v2版本中的自定义链接增加一个功能，就是每次上传的时候连接里的版本号都能加1，因为我使用github actions上传到npm每次都会自动增加版本号
![image](https://github.com/XPoet/picx/assets/114545939/672b4e47-3b87-460f-92f3-08aaa31ad3fb)

**Comment by XPoet** [comment]
这个功能通用性不强，还是自己手动添加吧
