### ISSUE TITLE
大佬这个图床可以接入网站吗？有接入网站的api吗？

### ISSUE THREAD

**Issue by klmahua** [XPoet/picx#32]
大佬这个图床可以接入网站吗？有接入网站的api吗？想接入网站使用，网站上传后可以同步上传到图床。。。

**Comment by XPoet** [comment]
PicX 使用的是 GitHub API，你了解下，实现你的需求不难的

**Comment by klmahua** [comment]
比较小白，能出个简单的接入教程吗

**Comment by XPoet** [comment]
https://docs.github.com/en/rest
看 GitHub 官方文档

**Comment by klmahua** [comment]
哦、、、感谢回答，，，有空研究一下
