### ISSUE TITLE
复制不了，也不会弹窗提示，文件传上去了

### ISSUE THREAD

**Issue by amiaoapp** [XPoet/picx#323]
我看了其他人提的issues，不是说插件问题，就说是自己问题

我换了chrome，safari

safari没任何插件给了所有权限，依然不能复制，不会写到剪切板。

chrome也是，好久了，老哥，你确定这不是设计缺陷？

就算不能自己写到剪切板，也应该显出来最终生成的图床链接吧，现在就看到图提示上传成功了，但是下面的蓝色文字点了没反应。
f12也看不到

<img width="1378" alt="16907" src="https://github.com/user-attachments/assets/75de0292-637f-4753-9597-1244291b5dd5">

<img width="1365" alt="8925" src="https://github.com/user-attachments/assets/d5b46445-14c2-40d9-aa34-992f8b35f401">

**Comment by XPoet** [comment]
首先，自动复制和手动复制图片链接到剪贴板的功能都是可以用，我这边 Chrome、Edge、Safari 测试都是没有问题的。
请检查一下你的浏览器是否禁止了  https://picx.xpoet.cn 这个网站的复制到剪贴板功能。
百度、谷歌搜一下都能知道解决方法

**Comment by XPoet** [comment]
看到有控制台报错，请退出，清除一下缓存，重新登录试试

**Comment by amiaoapp** [comment]
> 看到有控制台报错，请退出，清除一下缓存，重新登录试试

<img width="1365" alt="62349" src="https://github.com/user-attachments/assets/8ac8b757-acd9-4349-b1df-0637c90d2c06">

解决不了，我也清了缓存，啥权限都给了

我其实想提个建议，咱可以把生成的图片链接展示到下方吗》？像很多图床工具一样，上传完后会在下方列出来，markdown ，html等

<img width="1322" alt="21239" src="https://github.com/user-attachments/assets/3f75b0f2-9497-4860-bd6e-7dc2da861409">

<img width="1342" alt="93511" src="https://github.com/user-attachments/assets/07603900-1a6d-499c-8855-4893d1d70407">

我不折腾了，等你更新把，我折腾了好久了，咋都不行。我是心服口服了。感谢大佬的无私奉献，很好用

**Comment by XPoet** [comment]
后续版本增加显示完整的图片链接功能。

**Comment by XPoet** [comment]
我又测试很多遍，一直正常。
你换台电脑试试看还有没有这个问题？

**Comment by amiaoapp** [comment]
> 我又测试很多遍，一直正常。 你换台电脑试试看还有没有这个问题？

嗯，不试了，等你后续加了链接显示，我再用吧

**Comment by amiaoapp** [comment]
> 我又测试很多遍，一直正常。 你换台电脑试试看还有没有这个问题？

老哥你要不要远程我一下，如果可以的话

**Comment by amiaoapp** [comment]
换token登录可以了，用oauth登录报错。
