### ISSUE TITLE
提个需求：能否在图床管理界面增加图片压缩，就是针对已上传的图显示是否压缩过，以及支持二次压缩

### ISSUE THREAD

**Issue by amiaoapp** [XPoet/picx#325]
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/af674bf3-6349-46cf-9b8c-ed1b68f11d22">

咱们这个工具很好用，但是有时候需要用其他方式上传到github仓库。像用picgo上传，图片没转换和压缩，所以就想在图床管理界面查看已上传的图片时，对未做压缩的图片进行二次处理。而不改变图片名称。

picgo的插件太难用了，用obsidian上传图片得调用picogo，而没办法直接调用picx

**Comment by XPoet** [comment]
这个不太好实现，后续看实际情况
