### ISSUE TITLE
请问, 批量上传文件的时候, 能否一次性返回所有的图片链接,方便复制, 而不用一张张的把图片链接复制出来. 

### ISSUE THREAD

**Issue by Tongvivi** [XPoet/picx#326]
请问, 批量上传文件的时候, 能否一次性返回所有的图片链接,方便复制, 而不用一张张的把图片链接复制出来. 我经常需要上传20 30张图, 或者有什么好的办法, 能一次复制全部的上传好的图片链接地址. 谢谢

**Comment by XPoet** [comment]
现在就是支持的，你批量上传成功后，就会把图片链接批量复制到剪贴板，直接粘贴就有
