### ISSUE TITLE
仓库设为私有后图床图片无法显示

### ISSUE THREAD

**Issue by elfcute** [XPoet/picx#332]
![image](https://github.com/user-attachments/assets/79ffb722-1ca4-44db-a713-71111f1544a3)
![image](https://github.com/user-attachments/assets/d9e34995-1bab-4205-8023-09d7738149d5)

登录方式是token，我看这个token选择的时候是对私有仓库的完全控制，为啥设为私有还会无法显示图片？

设为私有的原因是因为上传的图片，别人点开都能看见我的仓库地址都能完全看见图床的所有图片。

**Comment by XPoet** [comment]
仓库必须 public！
