### ISSUE TITLE
国内不可见么

### ISSUE THREAD

**Issue by box96** [XPoet/picx#333]
国内不可见么，不翻图片就刷新不出来

**Comment by samling-jackyjyo** [comment]
因该是github被屏蔽的原因吧

**Comment by XPoet** [comment]
详情看一下文档介绍
https://picx-docs.xpoet.cn/usage-guide/settings.html#%E5%9B%BE%E7%89%87%E9%93%BE%E6%8E%A5%E8%A7%84%E5%88%99%E9%85%8D%E7%BD%AE

<img width="733" alt="image" src="https://github.com/user-attachments/assets/4abb48f3-d905-4b81-9bb0-7ea534c00220">

**Comment by XPoet** [comment]
给你的 GitHub Pages 服务绑定一个自定义域名就能完美避开墙的状态

**Comment by XPoet** [comment]
上网搜
