### ISSUE TITLE
建议图床配置选择自动目录后每天可以更新目录

### ISSUE THREAD

**Issue by ZephXu07** [XPoet/picx#36]
如题，刚开始使用的前几天没发觉，这两天才发现一直使用的是第一天配置的自动目录，然后每一天都需要勾选其他选项再选择回去才会生成新的目录

**Comment by XPoet** [comment]
挺好的建议 👍，改天加上去

**Comment by cody1991** [comment]
+1。。

**Comment by XPoet** [comment]
该功能已上线 https://picx.xpoet.cn/
清空一下浏览器缓存 或 多刷新几遍即可
