### ISSUE TITLE
萌新问一下，怎么安装呀，运行目录设置public也没用

### ISSUE THREAD

**Issue by taotutuchuang** [XPoet/picx#4]
能告诉我一下吗，谢谢了

**Comment by XPoet** [comment]
@taotutuchuang 不用安装，打开这个网站：**picx.xpoet.cn** ，在**配置**那里填好你的信息就能用了。

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/97133440-09f3e480-1785-11eb-99a6-55bc2da21935.png)

**Comment by taotutuchuang** [comment]
数据库导入，还有数据库账户和密码设置



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "指间的诗意"<notifications@github.com&gt;; 
发送时间: 2021年1月8日(星期五) 上午9:53
收件人: "XPoet/picx"<picx@noreply.github.com&gt;; 
抄送: ":-)"<8859443@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [XPoet/picx] 萌新问一下，怎么安装呀，运行目录设置public也没用 (#4)





 
Closed #4.
