### ISSUE TITLE
批量上传图片哈希化

### ISSUE THREAD

**Issue by RealKiro** [XPoet/picx#40]
- 在批量上传图片时“哈希化”可以增加批量选择功能吗？不希望哈希化就需要一个一个取消勾选很麻烦

**Comment by XPoet** [comment]
很好的建议，后续版本加上 ｂ(￣▽￣)ｄ

**Comment by klmahua** [comment]
支持，，，，批量上传了图片结果都重命名了。。。网站都不识别了

**Comment by XPoet** [comment]
目前无论是单个上传还是批量上传，均会自动开启 hash
