### ISSUE TITLE
希望图床管理增加上传功能，目前只有删除？

### ISSUE THREAD

**Issue by klmahua** [XPoet/picx#43]
希望图床管理增加上传功能，目前只有删除？如果有很多文件夹，每次上传难道都需要配置一下的吗？

**Comment by XPoet** [comment]
1. PicX 本身就有上传功能，不需要放在图床管理那里去。
2.  只需配置一次，下次使用会读取之前的配置，除非你把浏览器里面的 localStorage 删掉了
![image](https://user-images.githubusercontent.com/24516169/117977453-686c6300-b363-11eb-8f81-80e2a15f7f17.png)
