### ISSUE TITLE
能不能写个搭建的教程

### ISSUE THREAD

**Issue by akaryc1b** [XPoet/picx#49]
自己试了好久 好像少环境

**Comment by akarysxt** [comment]
谢谢已经搭建好了

**Comment by iso-lib** [comment]
> 谢谢已经搭建好了

那你还不写个搭建教程回馈社会?
虽然作者的网站很好用,,但就怕哪天跑路了

**Comment by XPoet** [comment]
@iso-lib 
@akaryc1b 
作者不会跑路
没必要自己额外搭建一个站点，用 picx.xpoet.cn 就好了，长期维护+升级
