### ISSUE TITLE
这个图床网站在关机重启后token就失效了，是否能能弄个直接永久登陆的。

### ISSUE THREAD

**Issue by heguohui2018** [XPoet/picx#5]

**Comment by heguohui2018** [comment]
不用了，我直接将token存成代码片段，每次调取，感谢作者提供这么好用的工具。

**Comment by XPoet** [comment]
谢谢支持，token 存储跟关机重启无关，它永久存储在浏览器的 `localStorage` 里面，除非你清空了浏览器缓存。
