### ISSUE TITLE
支持默认上传完的链接形式为Markdown

### ISSUE THREAD

**Issue by biuaxia** [XPoet/picx#50]
如题，希望能够支持默认上传后的链接就Markdown。可以增加一个配置。

**Comment by XPoet** [comment]
下个版本增加该配置项

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/133744963-5d205891-07bc-4076-8589-22e122ab3d0a.png)

![image](https://user-images.githubusercontent.com/24516169/133744880-33777894-0011-45aa-bbbc-a3587335a521.png)

该功能已上线 https://picx.xpoet.cn/
请清空一下浏览器缓存 或 多刷新几遍浏览器
