### ISSUE TITLE
您好，会有一次添加多张图片功能的考虑吗？

### ISSUE THREAD

**Issue by zyu0** [XPoet/picx#51]

**Comment by zyu0** [comment]
问题表述不够清晰，目前的尝试中多张上传需要一张张拖过来，尝试选择多张拖进来只会选取最后一张，能否做到选择多张拖进来就变成多张上传呢？

**Comment by XPoet** [comment]
目前支持批量选择多张图片，同时拖拽多张图片，好像不支持，下个版本加上

**Comment by zyu0** [comment]
hh，期待
