### ISSUE TITLE
现在token粘贴上不能用是怎么回事

### ISSUE THREAD

**Issue by qianhuiya** [XPoet/picx#52]
![E}E2R3HFU6 E)F$0PCO80GM](https://user-images.githubusercontent.com/55833213/122640002-8e89dd80-d12f-11eb-919e-4aa340413cdc.png)

**Comment by XPoet** [comment]
你的意思的 复制了 token 粘贴到 token 输入框无效吗？请检查你的剪贴板是否成功粘贴了 token
