### ISSUE TITLE
如何在自己的服务器上面搭建

### ISSUE THREAD

**Issue by FeiFei-SS** [XPoet/picx#58]
我上传到了我自己的伺服器，但是打开页面是空白

**Comment by FeiFei-SS** [comment]
我上传到了我自己的伺服器，但是打开页面是空白

**Comment by XPoet** [comment]
不建议部署别的服务器上，直接在 https://picx.xpoet.cn/ 使用即可，作者会一直维护升级

**Comment by FeiFei-SS** [comment]
那我可以自己部署吗？

**Comment by XPoet** [comment]
可以，但没那个必要

**Comment by qvqz** [comment]
我也想部署，我打开也是白色。咋办呀大佬

**Comment by XPoet** [comment]
没必要额外部署，直接在 https://picx.xpoet.cn/ 使用即可，作者会一直维护升级。
你要是自己部署一套，出了问题都不知道怎么解决，强烈建议在 https://picx.xpoet.cn/ 使用，永久稳定，不断升级。
如果你确实要自己部署，使用 `npm run build` 打包，再部署打包后的静态文件。

**Comment by FeiFei-SS** [comment]
具体说说怎么弄呢

**Comment by XPoet** [comment]
@FeiFei-SS 
你有自己服务器却不会部署？？
请自行查阅服务器厂商文档

**Comment by FeiFei-SS** [comment]
node.js版本?

**Comment by CAB233** [comment]
@FeiFei-SS fork作者的仓库，然后在vercel直接部署就好了
