### ISSUE TITLE
开发环境有问题，但是打包没问题是怎么回事啊

### ISSUE THREAD

**Issue by 768119359** [XPoet/picx#59]
![image](https://user-images.githubusercontent.com/57691895/127362530-ef587e43-8d84-4e1b-a73d-66086b3c0d86.png)
:sob:
希望大佬能帮忙看下，我想集成这个功能到我个人使用的应用里

**Comment by XPoet** [comment]
没必要额外部署，直接在 https://picx.xpoet.cn/ 使用即可，作者会一直维护升级。
你要是自己部署一套，出了问题都不知道怎么解决，强烈建议在 https://picx.xpoet.cn/ 使用，永久稳定，不断升级。
如果你确实要自己部署，使用 `npm run build` 打包，再部署打包后的静态文件。

**Comment by XPoet** [comment]
你把 https://picx.xpoet.cn/ 链接放到你的个人应用里即可。

**Comment by XPoet** [comment]
Windows 系统 dev 有点问题。、
先在 main.ts 注释以下代码
```ts
if (import.meta.env.MODE === 'production') {
  import('@/common/utils/registerSW')
}
```

运行起来后再解除注释

**Comment by 768119359** [comment]
好的，感谢解答:smile:
