### ISSUE TITLE
建议支持 OAuth 登录

### ISSUE THREAD

**Issue by hmsjy2017** [XPoet/picx#60]
token难记，登录不太方便。建议支持 OAuth 登录。

**Comment by XPoet** [comment]
后续版本加上

**Comment by WangQuan-cn** [comment]
当前如果使用chrome的话，可以将token记录到google的密码本上

> token难记，登录不太方便。建议支持 OAuth 登录。

**Comment by XPoet** [comment]
通过 GitHub OAuth 授权登录获取的 Token，只要只读的权限，无法操作仓库。

作者考虑通过 GitHub  APP 来实现，但第一次的授权的步骤比较多

**Comment by XPoet** [comment]
PicX 已支持 GitHub OAuth 登录，详情查看 [文档教程](https://picx-docs.xpoet.cn/docs/usage-guide/config.html#github-oauth-%E6%8E%88%E6%9D%83%E7%99%BB%E5%BD%95)

在图床配置页面可以进行切换。

<img width="1008" alt="image" src="https://github.com/XPoet/picx/assets/24516169/87333d8d-2a6d-4c62-9b73-d7b6553becfd">

<img width="1016" alt="image" src="https://github.com/XPoet/picx/assets/24516169/60433e24-38a3-4f18-ae3a-357e1a423d0b">
