### ISSUE TITLE
界面点击删除时是否支持jsdelivr同步删除

### ISSUE THREAD

**Issue by tsvico** [XPoet/picx#63]
目前在网上找到的方案是
主动访问一下刷新地址
原图片地址 `https://cdn.jsdelivr.net/gh/xx/xx/xx1.png`
刷新地址    `https://purge.jsdelivr.net/gh/xx/xx/xx1.png`

**Comment by XPoet** [comment]
jsdelivr 有缓存，时效大概几个小时到一天。
我研究研究一下，后续版本加上

**Comment by XPoet** [comment]
删除图片后，已增加刷新 `https://purge.jsdelivr.net/gh/xx/xx/xx1.png`
但效果不太明显
