### ISSUE TITLE
GitHub API 的分页数据处理

### ISSUE THREAD

**Issue by happyflyer** [XPoet/picx#64]
配置图床的时候，访问GitHub API获取的数据是分页的，只有部分，找不到之前图床的那个repo了，请教如何解决

**Comment by XPoet** [comment]
这个问题作者没考虑到，目前需要你删掉一些无用的仓库，我30+仓库，正常使用

**Comment by XPoet** [comment]
我优先解决这个问题，需要等待几天

**Comment by XPoet** [comment]
该问题已修复，进入 picx.xpoet.cn 刷新一下就好了。目前能显示最新创建的前 100 个仓库，基本能满足使用了
