### ISSUE TITLE
不想要默认勾选hash可以吗

### ISSUE THREAD

**Issue by oyzbmmmm** [XPoet/picx#65]
不想要默认勾选hash可以吗

**Comment by XPoet** [comment]
可以的，作者正准备加上这个功能

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/133744510-5a67d2fc-8563-43d3-970c-5b544400c248.png)

该功能已上线 https://picx.xpoet.cn/ 
请清空一下浏览器缓存 或 多刷新几遍浏览器
