### ISSUE TITLE
建议可以配置自动图片命名格式，比如以各种格式的日期命名那种

### ISSUE THREAD

**Issue by nigeder** [XPoet/picx#67]
谢谢！

**Comment by XPoet** [comment]
后续会考虑加上该功能，近期会有新版本迭代

**Comment by XPoet** [comment]
通过拖拽、粘贴或选择图片到 PicX 目前是会给图片加 hash 码，类似于自动命名，经考究，楼主提的需求实用意义不大，放弃开发。
