### ISSUE TITLE
图床管理界面未能显示全部已经上传了的图片

### ISSUE THREAD

**Issue by aaronmack** [XPoet/picx#68]
在A，B两台电脑上同时使用PicX,A电脑往往只显示A电脑上传过的图片，不显示B电脑上传的

1）刷新页面 2）重新配置  都没有办法全部显示

3）退出登录，重新登录 可以全部显示

请问是我的操作不太正确，还是就是这样的机制？

感谢

**Comment by XPoet** [comment]
目前是这样的 ，后续会在图床管理页增加刷新按钮来重新加载所有图片资源

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/132152430-7821eb93-24df-497c-a455-a8eccdcf5ac2.png)

该问题已解决，如上图，点击 “重新加载图片” 按钮即可同步在不同设备上传的图片
