### ISSUE TITLE
无法上传图片，显示403

### ISSUE THREAD

**Issue by zhangjin38416** [XPoet/picx#69]
Code: 403, Message: API rate limit exceeded for 192.132.225.129. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by wangxinzhi0** [comment]
上传失败，Code:404, Message: Not Found

**Comment by XPoet** [comment]
已修复，现可正常使用。如果还出现该错误，多刷新几次浏览器，或清空一下 picx.xpoet.cn 网站的缓存，或退出重新登录。
