### ISSUE TITLE
上传图片接口https://api.github.com/repos/github-user/repo-name/contents/xxx/xxx.jpg报错404

### ISSUE THREAD

**Issue by hashqueue** [XPoet/picx#70]
首先感谢作者大大的图床工具，辛苦您了。

报错如下：`Code：404，Message：Not Found`

![微信图片_20210905153247](https://user-images.githubusercontent.com/42225052/132119203-d8129049-8cbf-463a-bd58-e0e94e7f2251.png)

**Comment by shfshanyue** [comment]
我最近也出现了

**Comment by XPoet** [comment]
已修复，现可正常使用。如果还出现该错误，多刷新几次浏览器，或清空一下 picx.xpoet.cn 网站的缓存，或退出重新登录。

**Comment by hashqueue** [comment]
现在已经可以正常使用了，再次感谢作者大大~

**Comment by shfshanyue** [comment]
现在已经可以正常使用了，再次感谢作者大大~
