### ISSUE TITLE
能不能一键转为markdown格式？

### ISSUE THREAD

**Issue by YYbooks0** [XPoet/picx#73]
每次上传后都需要一个个点，希望能添加！

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/133744963-5d205891-07bc-4076-8589-22e122ab3d0a.png)

![image](https://user-images.githubusercontent.com/24516169/133744880-33777894-0011-45aa-bbbc-a3587335a521.png)

该功能已上线 https://picx.xpoet.cn/
请清空一下浏览器缓存 或 多刷新几遍浏览器

**Comment by YYbooks0** [comment]
> ![image](https://user-images.githubusercontent.com/24516169/133744963-5d205891-07bc-4076-8589-22e122ab3d0a.png)
> 
> ![image](https://user-images.githubusercontent.com/24516169/133744880-33777894-0011-45aa-bbbc-a3587335a521.png)
> 
> 该功能已上线 https://picx.xpoet.cn/
> 请清空一下浏览器缓存 或 多刷新几遍浏览器

好的！太感谢了！
