### ISSUE TITLE
非常好用，但是有个问题

### ISSUE THREAD

**Issue by tjyuli** [XPoet/picx#8]
清空了浏览器缓存怎么找回以前的链接？

**Comment by XPoet** [comment]
@tjyuli 清空缓存后，重新填写配置，然后打开管理页面就会出现仓库里的图片外链

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/103170978-6e194e80-4883-11eb-8152-4d34a7928980.png)
