### ISSUE TITLE
令牌不能绑定

### ISSUE THREAD

**Issue by huanghe24** [XPoet/picx#80]
创建了令牌，也点了 repo 但是依旧不能绑定

**Comment by XPoet** [comment]
请描述详细一点，怎么不能绑定？在哪个环节？最好附带截图

**Comment by huanghe24** [comment]
我创建了令牌勾选了repo（也只勾选了这个）
![image-20211011090450308](https://user-images.githubusercontent.com/80388376/136720186-aa5e350e-d688-4850-9f26-f22896769ca3.png)


生成了令牌
![image-20211011090558615](https://user-images.githubusercontent.com/80388376/136720264-fc808b0e-1c40-4a19-a646-0cb1760734fc.png)

下面是配置时的显示
![image-20211011090707123](https://user-images.githubusercontent.com/80388376/136720351-b79e021d-9cb1-43ce-835c-faf6bac187d0.png)

**Comment by huanghe24** [comment]
还是一样，有其他人遇到和我一样的问题吗？
