### ISSUE TITLE
您好 我可以把你的picx网页封装成apk吗 

### ISSUE THREAD

**Issue by boluofan** [XPoet/picx#84]
#### 可以把你的picx网页封装成apk吗？把你的图床网站套壳封装成apk 也是开源免费的
![Screenshot_2021_1019_152349](https://user-images.githubusercontent.com/40459801/137862977-7914eafa-f392-43bd-a727-ff98c12a5422.jpg)
-------------------
#### 方便将手机上的图片上传到GitHub图床 而且还可以直接调用相机拍照上传😀
![微信图片_20211019152929](https://user-images.githubusercontent.com/40459801/137863661-5184e3db-71f0-43e8-8ba7-1495992a4763.jpg)

-------------------

#### 这是apk的下载链接
https://wws.lanzoui.com/iqOG8vizm7i
#### 密码:g5e1

**Comment by boluofan** [comment]
你好 我更新了apk。禁止了页面缩放并取消了定位权限、同时禁止了应用屏幕旋转 。你可以根据这个apk适配页面😀

**Comment by RuikangSun** [comment]
您好！请问您是如何将网页打包成APP的呢？有没有什么开源的工具？谢谢！
