### ISSUE TITLE
建议增加刷新文件夹功能

### ISSUE THREAD

**Issue by boluofan** [XPoet/picx#85]
你好，我对你的图床网站进行了apk封装所以产生了一个问题。
比如，我在电脑网页端和手机app端都登录了同一个仓库账户。但在pc网页端新创建了一个文件夹后，手机端再刷新也不可以同步该文件夹，只能清理token后重新登录获取文件夹列表。
可以为该刷新按钮加上刷新仓库文件夹列表的功能吗，这样点击就可刷新、同步文件夹
![image](https://user-images.githubusercontent.com/40459801/138021204-e97b163d-6922-4de6-bd4d-7bdc3b56673a.png)

**Comment by XPoet** [comment]
PicX 已支持多级目录和刷新文件夹功能
![image](https://user-images.githubusercontent.com/24516169/147431047-05b6107f-8fa5-4f9e-9d48-f372096d1400.png)

**Comment by boluofan** [comment]
NB👍
