### ISSUE TITLE
建议复制CDN外链时取消”@分支“字段

### ISSUE THREAD

**Issue by BNQDZJ** [XPoet/picx#87]
jsdelivr有个缓存机制（好像是每48小时自动更新一次），图片删除后第二次上次重名图片不会实时更新，在取消”@分支“字段后在访问的同时会调用刷新缓存的API（相当于手动更新了一次），达到了实时更新的目的
链接格式
原外链 https://cdn.jsdelivr.net/gh/*****/******@main/*.png
取消”@分支“字段后 https://cdn.jsdelivr.net/gh/*****/******/*.png

Tips：CDN节点全部更新需要大约30秒，所以仍可能在部分地区看到的图片依然是旧的，但相较于48小时来说30秒已经很快了

**Comment by XPoet** [comment]
之前有做刷新缓存的处理，效果不明显

**Comment by BNQDZJ** [comment]
请问刷新缓存指的是什么？
如果刷新缓存是指jsdelivr话，那么jsdelivr检测到访问后后台会自动调用刷新缓存API，无需让Picx调用，只要Picx复制CDN链接的时候去掉@分支的字段就行了
如果刷新缓存是指Picx的话。。。目前还没有遇到关于Picx的缓存问题

**Comment by XPoet** [comment]
去掉 @分支 不行，PicX 支持多分支管理
