### ISSUE TITLE
在Picx上传图片后在GitHub处删除Picx仍显示

### ISSUE THREAD

**Issue by BNQDZJ** [XPoet/picx#88]
在picx上传图片后在GitHub处删除picx仍显示，且在尝试打开图片时提示404，刷新文件夹功能也没用
![](https://user-images.githubusercontent.com/64721413/141998236-b492a555-2d14-44e8-b27f-67cd94d6c2b0.png)
![](https://user-images.githubusercontent.com/64721413/141998240-0de98956-4763-4432-8c5c-5998b6107265.png)

**Comment by XPoet** [comment]
看你使用了多级目录来存储，PicX 暂未完成支持多级目录。
你得退出，重新登录一下。
