### ISSUE TITLE
token验证失败

### ISSUE THREAD

**Issue by linzefan0612** [XPoet/picx#89]
![image](https://user-images.githubusercontent.com/52768739/142218465-cff4663d-cc1a-462e-bf03-950bc604c1b9.png)
这个token也是刚创建的呀！跟着教程走的

**Comment by Somnus711** [comment]
我也是401 跟着教程走的 token给的repo权限 自己在bash行curl -u username:token https://api.github.com/user 都能调通

**Comment by XPoet** [comment]
我刚刚测试了 PicX 能正常使用，Chrome 最新浏览器。
@linzefan0612 
@Somnus711 
请使用 Chrome 或 Edge 最新版本浏览器 。
或提供下你们使用 PicX 的操作系统，浏览器及浏览器版本，方便我排查。

**Comment by NagaseKouichi** [comment]
同样遇到这个问题，WIN10系统，EDGE最新版本 95.0.1020.53 (官方内部版本) (64 位)

**Comment by XPoet** [comment]
@NagaseKouichi 
经过测试我这边的 Edge 浏览器可以正常使用，暂不清楚具体原因
1、请确认 token 是否正确
2、彻底清空浏览器缓存，再试一次
3、还不行就搭把梯子再试

**Comment by XPoet** [comment]
@NagaseKouichi 
经过测试我这边的 Edge 浏览器可以正常使用，暂不清楚具体原因
1、请确认 token 是否正确
2、彻底清空浏览器缓存，再试一次
3、还不行就搭把梯子再试

**Comment by Somnus711** [comment]
问题解决了 换了火狐浏览器顺利登录了 用chrome不行

**Comment by ctaoist** [comment]
Chrome 下确实有问题，我用 Chrome 也是出现同样的错误，换 Firefox 一次就成功。

ps. 系统：win10 企业版 19042；Chrome 版本：90.0.4430.72（正式版本） （32 位）

@XPoet
