### ISSUE TITLE
建议加入Statically CDN

### ISSUE THREAD

**Issue by BNQDZJ** [XPoet/picx#90]
导言：jsdelivr的限制增加了仓库总存储超过50MB的会停止加速服务，当图片过多超过50MB时就没法使用加速了，需要另寻CDN加速服务

Statically CDN 使用了Anycast CDN（Anycast Internet Acceleration，AIA）中国大陆大概率分配使用日本东京的节点，据说有国内节点，但十次有九次是海外的，不是美国，加拿大就是日本，韩国，但速度还不错，比jsdelivr的CloudFlare快了一点，CloudFlare在中国有节点，但是不用，一直都是走美西的节点

Tips:jsdelivr主要用CloudFlare其次是fastly，Statically正好相反

使用方式 https://cdn.staticaly.com/gh/:user/:repo/:tag/:file

**Comment by XPoet** [comment]
good

**Comment by BNQDZJ** [comment]
打错了，域名是cdn.staticaly.com 已修改
cdn.statically.io是面向海外用户的，访问会显示连接超时

**Comment by XPoet** [comment]
OK

**Comment by ctaoist** [comment]
这个 CDN 功能还挺强，就是 `cdn.staticaly.com` 相比于 `cdn.statically.io` 中间少个 `l`，开始没注意打错了。不过在官网看到一段话：

>All Statically's services starts with this URL:
`https://cdn.statically.io`
If you are still using the old URL `https://cdn.staticaly.com`, please use the above instead.

里面说 `https://cdn.staticaly.com` 是老旧的 URL，就是不知道以后会不会被取消，毕竟 `cdn.statically.io` 国内访问不了。

**Comment by BNQDZJ** [comment]
> 这个 CDN 功能还挺强，就是 相比于 中间少个 ，开始没注意打错了。不过在官网看到一段话：`cdn.staticaly.com``cdn.statically.io``l`
> 
> > 所有 Statically 的服务都以此 URL开头：如果您仍在使用旧 URL ，请改用上述 URL。`https://cdn.statically.io``https://cdn.staticaly.com`
> 
> 里面说 是老旧的 URL，就是不知道以后会不会被取消，毕竟 国内访问不了。`https://cdn.staticaly.com``cdn.statically.io`

已经提了Issue了但是没回复，公告说这几天在开发新功能可能回复会比较慢，过几天发封邮件问问
cdn.statically.io的cdn他说已经从Fastly改成CloudFlare了，但访问好像还是不行
