### ISSUE TITLE
上传的时候。如何配置默认重命名

### ISSUE THREAD

**Issue by yaoGrace** [XPoet/picx#91]
上传的时候。如何配置默认重命名

**Comment by XPoet** [comment]
当前版本不支持，下个版本加上

**Comment by XPoet** [comment]
PicX 已支持配置图片命名前缀
![image](https://user-images.githubusercontent.com/24516169/147430243-4c844731-234f-416c-bf73-22a868009ddb.png)
![image](https://user-images.githubusercontent.com/24516169/147430264-62988cc7-a00d-4e14-9ada-085cf4208fab.png)
