### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by qianweikhm** [XPoet/picx#92]
问题：
上传图片失败

错误：
Code: 404, Message: Not Found
上传失败
<img width="920" alt="Snipaste_2021-11-30_09-33-33" src="https://user-images.githubusercontent.com/33917348/143969587-c5a268d5-b4c0-4f26-8520-cb82d3b2b0d4.png">

**Comment by XPoet** [comment]
你退出，重新配置登录再试试
